"action_createpoi": lage et POI (interessant punkt)
"hint_pointselected": punkt valgt\n(shift+trykk punktet for å\nstarte en ny linje)
"action_movepoint": flytter punkt
"hint_drawmode": trykk for å legge til punkt\ndobbeltklikk eller enter\nfor å avslutte linje
"hint_overendpoint": over endepunkt\ntrykk for å koble sammen\nshift+trykk for å slå sammen
"hint_overpoint": over punkt\ntrykk for å koble sammen
"gpxpleasewait": Vennligst vent mens sporloggen behandles.
"revert": Tilbakestill
"cancel": Avbryt
"prompt_revertversion": "Tilbakestill til tidligere lagret versjon:"
"tip_revertversion": Velg versjonen det skal tilbakestilles til
"action_movepoi": flytter et POI (interessant punkt)
"tip_splitway": Del vei i valgt punkt (X)
"tip_direction": Veiretning, trykk for å snu
"tip_clockwise": Sirkulær vei med klokka, trykk for å snu
"tip_anticlockwise": Sirkulær vei mot klokka, trykk for å snu
"tip_noundo": Ingenting å angre
"action_mergeways": slår sammen to veier
"tip_gps": Vis GPS sporlogger (G)
"tip_options": Sett valg (velg kartbakgrunn)
"tip_addtag": Legg til merke
"tip_addrelation": Legg til i en relasjon
"tip_repeattag": Gjenta merker fra sist valgte vei (R)
"tip_alert": Det oppstod en feil, trykk for detaljer
"hint_toolong": "for lang til å låse opp:\nvennligst del opp\ni mindre veier"
"hint_loading": laster veier
"prompt_welcome": Velkommen til OpenStreetMap!
"prompt_introduction": "Velg en knapp nedenfor for å redigere. Hvis du velger 'Start' redigerer du kartet direkte, endringer blir vanligvis synlige hver torsdag. Hvis du velger 'Øve' lagres ikke endringer, så du kan øve deg på å redigere.\nHusk OpenStreetMaps gyldne regler:\n\n"
"prompt_dontcopy": Ikke kopier fra andre kart
"prompt_accuracy": Nøyaktighet er viktig, bare kartlegg steder du har besøkt
"prompt_enjoy": Og ha det morsomt!
"dontshowagain": Ikke vis denne meldingen igjen
"prompt_start": Begynn å kartlegge med OpenStreetMap.
"prompt_practise": Øv på kartlegging, endringer blir ikke lagret.
"practicemode": Øvelsesmodus
"help": Hjelp
"prompt_help": Finn ut hvordan du bruker Potlatch, programmet for kartredigering.
"track": Spor
"prompt_track": Overfør dine GPS-sporinger til (låste) veier for redigering.
"action_deletepoint": sletter et punkt
"deleting": sletter
"action_cancelchanges": avbryter endringer av
"emailauthor": \n\nVennligst send en epost (på engelsk) til richard\@systemeD.net med en feilrapport, og forklar hva du gjorde når det skjedde.
"error_connectionfailed": "Beklager - forbindelsen til OpenStreetMap-tjeneren feilet, eventuelle nye endringer har ikke blitt lagret.\n\nVil du prøve på nytt?"
"option_background": "Bakgrunn:"
"option_fadebackground": Fjern bakgrunn
"option_thinlines": Bruk tynne linjer uansett forstørrelse
"option_custompointers": Bruk penn- og håndpekere
"tip_presettype": Velg hva slags forhåndsinstillinger som blir vist i menyen
"action_waytags": sette merker på en vei
"action_pointtags": sette merker på et punkt
"action_poitags": sette merker på et POI (interessant punkt)
"action_addpoint": legger til et punkt på enden av en vei
"add": Legg til
"prompt_addtorelation": Legg $1 til en relasjon
"prompt_selectrelation": Velg en relasjon som allerede finnes, eller lag en ny relasjon
"createrelation": Lag en ny relasjon
"tip_selectrelation": Legg til den valgte ruta
"action_reverseway": snur en vei bak fram
"tip_undo": Angre $1 (Z)
"error_noway": Fant ikke veien $1 så det er ikke mulig å angre. (Kanskje den ikke er på skjermen lenger?)
"error_nosharedpoint": Veiene $1 og $2 deler ikke noe punkt lenger, så det er ikke mulig å angre.
"error_nopoi": Fant ikke POI-et, så det er ikke mulig å angre. (Kanskje den ikke er på skjermen lenger?)
"prompt_taggedpoints": Noen av punktene på denne veien er merket. Vil du virkelig slette?
"action_insertnode": legge til et punkt på veien
"action_splitway": dele en vei
"editingmap": Redigerer kart
"start": Start
"play": Øve
"delete": Slett
"a_way": $1 en vei
"a_poi": $1 et POI
"action_moveway": flytter en vei
"way": Vei
"point": Punkt
"ok": Ok
"existingrelation": Legg til en relasjon som er her fra før
"findrelation": Finn en relasjon som inneholder
"norelations": Ingen relasjoner i området på skjermen
