services:
  web:
    build:
      context: .
    environment:
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - .:/app
      - /app/node_modules/
      - web-tmp:/app/tmp
      - web-storage:/app/storage
    networks:
      - web_network
    tmpfs:
      /tmp/pids/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: ./start.sh
    depends_on:
      - db
      - memcached
    env_file:
      - ohm-docker.dev.env

  memcached:
    image: memcached:latest
    ports:
      - '11211:11211'
    networks:
      - web_network

  db:
    image: ghcr.io/openhistoricalmap/db:0.0.1-0.dev.git.3101.ha4a4757
    ports:
      - "54321:5432"
    env_file:
        - ohm-docker.dev.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - web_network

volumes:
  web-tmp:
  web-storage:
  db-data:
    driver: local
    name: ohm_web_pg17

networks:
  web_network:
    driver: bridge
    