"action_createpoi": Einen Ort von Interesse (POI) erstellen
"hint_pointselected": Punkt ausgewählt\n(Shift+Punkt anklicken, um\n eine neue Linie zu erstellen)
"action_movepoint": Punkt verschieben
"hint_drawmode": Klicken, um Punkt hinzuzufügen\nDoppelklicken oder Eingabetaste zum Beenden der Linie
"hint_overendpoint": Überlappung mit Endpunkt\nKlicken zum Anschließen\nShift+Klick zum Verschmelzen
"hint_overpoint": Überlappung mit Punkt\nKlicken zum Anschließen
"gpxpleasewait": Bitte warten, während die GPX-Aufzeichnung (Track) verarbeitet wird.
"revert": Vorherige Version wiederherstellen
"cancel": Abbrechen
"prompt_revertversion": "Frühere Version wiederherstellen:"
"tip_revertversion": Version zur Wiederherstellung wählen
"action_movepoi": Ort von Interesse (POI) verschieben
"tip_splitway": Weg am ausgewählten Punkt auftrennen (x)
"tip_direction": Richtung des Weges - Klicken zum Ändern
"tip_clockwise": Geschlossener Weg im Uhrzeigersinn - Klicken zum Ändern der Richtung
"tip_anticlockwise": Geschlossener Weg gegen den Uhrzeigersinn - Klicken zum Ändern der Richtung
"tip_noundo": Es gibt nichts rückgängig zu machen.
"action_mergeways": Zwei Wege verschmelzen
"tip_gps": GPS-Aufzeichnungen (Tracks) einblenden (g/G)
"tip_options": Optionen ändern (Kartenhintergrund)
"tip_addtag": Attribut (Tag) hinzufügen
"tip_addrelation": Zu einer Relation hinzufügen
"tip_repeattag": Attribute (Tags) vom vorher markierten Weg übernehmen (R)
"tip_alert": Ein Fehler ist aufgetreten - Klicken für Details
"hint_toolong": "Zu lang zum Entsperren:\nBitte in kürzere Wege aufteilen"
"hint_loading": Wege werden geladen
"prompt_welcome": Willkommen bei OpenStreetMap!
"prompt_introduction": "Bitte unten eine Schaltfläche anklicken, um mit dem Üben bzw. Editieren zu beginnen.\n\nStart: Jede Änderung wird sofort in der Datenbank gespeichert und wird beim nächsten Rendern berücksichtigt.\nÜben: Die Änderungen werden nicht gespeichert, es kann also nichts passieren. Bitte sicherstellen, dass unten rechts der Übungsmodus angezeigt wird.\n\nBeim Editieren bitte immer an die Goldenen Regeln von OpenStreetMap denken:\n\n"
"prompt_dontcopy": Nichts von anderen Karten kopieren / abzeichnen.
"prompt_accuracy": Fehlerfreiheit ist wichtig - nur Orte eintragen, die man kennt.
"prompt_enjoy": "Und: Viel Spaß!"
"dontshowagain": Diese Meldung nicht wieder anzeigen.
"prompt_start": Kartographieren in OpenStreetMap beginnen
"prompt_practise": Kartographieren üben - die Änderungen werden nicht gespeichert.
"practicemode": Übungsmodus
"help": Hilfe
"prompt_help": Anleitung für Potlatch, diesen Karten-Editor
"track": GPS-Aufzeichnung
"prompt_track": Deine GPS-Aufzeichnungen (Tracks) in (gesperrte) Wege zum Editieren wandeln.
"action_deletepoint": Punkt löschen
"deleting": löschen
"action_cancelchanges": Änderungen an <b>$1</b> abgebrochen
"emailauthor": \n\nBitte maile an richard\@systemeD.net eine Fehlerbeschreibung, und schildere, was Du in dem Moment getan hast. <b>(Wenn möglich auf Englisch)</b>
"error_connectionfailed": Die Verbindung zum OpenStreetMap-Server ist leider fehlgeschlagen. Kürzlich erfolgte Änderungen wurden nicht gespeichert.\n\nNoch einmal versuchen?
"option_background": "Hintergrund:"
"option_fadebackground": Hintergrund halbtransparent
"option_thinlines": Dünne Linien in allen Auflösungen benutzen
"option_custompointers": Stift- und Hand-Mauszeiger benutzen
"tip_presettype": Art der Voreinstellungen wählen, die im Menü angeboten werden sollen
"action_waytags": Attribute (Tags) für Weg zuweisen
"action_pointtags": Attribute (Tags) für Punkt zuweisen
"action_poitags": Attribute (Tags) für Ort von Interesse (POI) zuweisen
"action_addpoint": Punkt am Ende des Wegs hinzufügen
"add": Hinzufügen
"prompt_addtorelation": $1 zu einer Relation hinzufügen
"prompt_selectrelation": Bestehende Relation zum Hinzufügen auswählen oder neue Relation erstellen
"createrelation": Eine neue Relation erstellen
"tip_selectrelation": Zur markierten Route hinzufügen
"action_reverseway": Wegrichtung umkehren
"tip_undo": $1 rückgängig machen (Z)
"error_noway": Der Weg $1 kann nicht gefunden werden (eventuell wurde der Kartenausschnitt verschoben), daher ist Rückgängigmachen nicht möglich.
"error_nosharedpoint": Die Wege $1 und $2 haben keinen gemeinsamen Punkt mehr, daher kann das Aufteilen nicht rückgängig gemacht werden.
"error_nopoi": Der Ort von Interesse (POI) kann nicht gefunden werden (vielleicht wurde der Kartenausschnitt verschoben?), daher ist Rückgängigmachen nicht möglich.
"prompt_taggedpoints": Einige Punkte auf diesem Weg tragen Attribute (Tags). Trotzdem löschen?
"action_insertnode": Punkt auf Weg hinzufügen
"action_splitway": Weg teilen
"editingmap": Karte editieren
"start": Start
"play": Üben
"delete": Löschen
"a_way": $1 einen Weg
"a_poi": $1 einen Ort von Interesse (POI)
"action_moveway": einen Weg verschieben
"way": Weg
"point": Punkt
"ok": OK
"existingrelation": Zu einer bestehenden Relation hinzufügen
"findrelation": Finde eine Relation, die $1 enthält
"norelations": Keine Relationen in diesem Gebiet
"advice_toolong": Zu lang zum Entsperren - Bitte in kürzere Wege aufteilen.
"advice_waydragged": Weg verschoben (Z zum Rückgängig-Machen)
"advice_tagconflict": Die Attribute (Tags) passen nicht zusammen (Z zum Rückgängig-Machen)
"advice_nocommonpoint": Die Wege (Ways) haben keinen gemeinsamen Punkt.
"option_warnings": Warnungen anzeigen
"reverting": Änderungen werden zurückgenommen
