"action_createpoi": "POI:n lisääminen"
"hint_pointselected": piste valittuna\n(shift-klikkaa pistettä\naloittaaksesi uuden tien)
"action_movepoint": pisteen lisääminen
"hint_drawmode": napsauta lisätäksesi pisteen\nKaksoisnapsauta tai paina enter päättääksesi tien
"hint_overendpoint": päätepisteen päällä\nnapsauta sulkeaksesi\nshift-napsauta yhdistääksesi
"hint_overpoint": pisteen päällä\nnapsauta yhdistääksesi"
"gpxpleasewait": Odota. GPX-jälkeä käsitellään.
"revert": Kumoa
"cancel": Peru
"prompt_revertversion": "Palauta aiempaan versioon:"
"tip_revertversion": Valitse palautettava versio
"action_movepoi": "POI:n siirtäminen"
"tip_splitway": Katkaise tie valitusta kohdasta (X)
"tip_direction": Tien suunta - napsauta kääntääksesi
"tip_clockwise": Myötäpäivään sulkeutuva tie - napsauta kääntääksesi
"tip_anticlockwise": Vastapäivään sulkeutuva tie - napsauta kääntääksesi
"tip_noundo": Ei kumottavaa
"action_mergeways": kahden tien yhdistäminen
"tip_gps": Näytä GPS-jäljet (G)
"tip_options": Asetukset (valitse kartan tausta)
"tip_addtag": Lisää uusi tagi
"tip_addrelation": Lisää relaatio
"tip_repeattag": Toista tagit viimeksi valitusta tiestä (R)
"tip_alert": Tapahtui virhe - napsauta saadaksesi lisätietoja
"hint_toolong": "liian pitkä vapautettavaksi:\nkatkaise\nlyhyempiin teihin"
"hint_loading": ladataan teitä
"prompt_welcome": "Tervetuloa OpenStreetMap:iin"
"prompt_introduction": "Valitse haluamasi tila. Jos valitset aloita, pääset muokkaamaan karttaa suoraan - muutokset päivittyvät pääsivun kartalle yleensä torstaisin. Jos valitset harjoittele, tekemiäsi muutoksia ei tallenneta mihinkään, eli voit harjoitella muokkausta.\n\nMuistathan OpenStreetMapin kultaiset säännöt:\n\n"
"prompt_dontcopy": Älä kopioi muista kartoista.
"prompt_accuracy": "Tarkkuus on tärkeää: muokkaathan vain paikkoja, joissa olet ollut."
"prompt_enjoy": Pidä hauskaa!
"dontshowagain": Älä näytä tätä viestiä enää.
"prompt_start": Aloita kartan muokkaus.
"prompt_practise": Harjoittele - muutoksiasi ei tallenneta.
"practicemode": Harjoitustila
"help": Ohje
"prompt_help": Kuinka käytän Potlatchiä, tätä editoria?
"track": Jälki
"prompt_track": Muunna GPX-jälki lukituiksi teiksi muokkausta varten
"action_deletepoint": pisteen poistaminen
"deleting": poistaminen
"action_cancelchanges": peruutetaan muutokset
"emailauthor": \n\nLähetäthän sähköpostia, jossa kerrot mitä olit tekemässä, osoitteeseen richard\@systemeD.net mieluiten englanniksi.
"error_connectionfailed": "Yhteyttä OSM-palvelimeen ei saatu. Tuoreita muutoksia ei ole tallennettu.\n\nHaluatko yrittää uudestaan?"
"option_background": "Tausta:"
"option_fadebackground": Himmeä tausta
"option_thinlines": Käytä aina ohuita viivoja
"option_custompointers": Käytä kynä- ja käsikohdistimia
"tip_presettype": Valitse, millaisia pohjia on tarjolla valikossa.
"action_waytags": tien tagien asettaminen
"action_pointtags": pisteen tagien asettaminen
"action_poitags": "POI:n tagien asettaminen"
"action_addpoint": pisteen lisääminen tien perään
"add": Lisää
"prompt_addtorelation": Lisää $1 relaatioon
"prompt_selectrelation": Valitse olemassa oleva relaatio, johon lisätään tai luo uusi.
"createrelation": Luo uusi relaatio
"tip_selectrelation": Lisää valittuun reittiin
"action_reverseway": tien kääntäminen
"tip_undo": Kumoa $1 (Z)
"error_noway": Tietä $1 ei löydy (ehkä vieritit siitä liian kauaksi), joten kumoaminen ei onnistu.
"error_nosharedpoint": Teillä $1 ja $2 ei enää ole yhteistä solmua, joten tien katkaisua ei voi perua.
"error_nopoi": "POI:ta ei löydetä (ehkä vieritit siitä liian kauaksi), joten peruminen ei onnistu."
"prompt_taggedpoints": Joihinkin tien pisteisiin on lisätty tageja. Haluatko varmasti perua?
"action_insertnode": pisteen lisääminen tiehen
"action_splitway": tien katkaisu
"editingmap": Muokataan karttaa
"start": Aloita
"play": Harjoittele
"delete": Poista
"a_way": $1 tie
"a_poi": $1 POI
"action_moveway": tien siirtäminen
"way": Tie
"point": Piste
"ok": Ok
"existingrelation": Lisää olemassa olevaan relaatioon
"findrelation": Find a relation containing
"norelations": Nykyisellä alueella ei ole relaatioita
"advice_toolong": Liian pitkän tien lukituksen poisto ei sallittu - katkaise lyhyemmiksi teiksi.
"advice_waydragged": Tietä siirrettiin (paina Z kumotaksesi)
"advice_tagconflict": Tagit eivät täsmää - tarkista asia
"advice_nocommonpoint": Tiet eivät jaa yhteistä pistettä
"option_warnings": Näytä siirtymisvaroitukset
"reverting": kumotaan
"prompt_helpavailable": Kaikkia muutoksia ei ole tallennettu. (Tallentaaksesi Potlatchissa valitse jokin muu tie tai muu piste kuin nykyinen)
