name: "open_street_map"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - selenium-default
    - selenium-de
    - selenium-nolang
    - postgres

  selenium-default:
    image: selenium/standalone-firefox
    restart: unless-stopped

  selenium-de:
    image: selenium/standalone-firefox
    restart: unless-stopped

  selenium-nolang:
    image: selenium/standalone-firefox
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: openstreetmap
      POSTGRES_USER: openstreetmap
      POSTGRES_PASSWORD: openstreetmap

volumes:
  postgres-data:
