"action_createpoi": Criando um ponto de interesse (POI)
"hint_pointselected": Ponto selecionado\n(clique no ponto pressionando o shift para\niniciar uma nova linha)
"action_movepoint": Movendo um ponto
"hint_drawmode": Clique para adicionar um ponto\nDuplo clique/Enter\npara finalizar a linha
"hint_overendpoint": Sobre o ponto final\nclique para ligar\nclique pressionando o shift para mesclar
"hint_overpoint": Sobre o ponto\nclique para conectar
"gpxpleasewait": Favor aguardar enquanto a trilha GPX é processada.
"revert": Reverter
"cancel": Cancelar
"prompt_revertversion": "Retornar a uma versão previamente salva:"
"tip_revertversion": Escolha a versão para reverter
"action_movepoi": Movendo um ponto de interesse (POI)
"tip_splitway": Dividir caminho no ponto selecionado
"tip_direction": Direção do caminho - clique para inverter
"tip_clockwise": Caminho circular no sentido horário - clique para inverter
"tip_anticlockwise": Caminho circular no sentido anti-horário - clique para inverter
"tip_noundo": Nada para desfazer
"action_mergeways": Mesclando dois caminhos
"tip_gps": Mostrar trilhas do GPS
"tip_options": Configurar opções (escolha o plano de fundo do mapa)
"tip_addtag": Adicionar um novo tag (rótulo)
"tip_addrelation": Adicionar a uma relação
"tip_repeattag": Repetir tags (rótulos) do caminho previamente selecionado (R)
"tip_alert": Ocorreu um erro - clique para mais informações
"hint_toolong": "Muito longo para destravar:\nfavor dividir em\ncaminhos mais curtos"
"hint_loading": Carregando caminhos
"prompt_welcome": Bem-vindo ao OpenStreetMap!
"prompt_introduction": "Escolha um botão abaixo para começar a editar. Se você clicar em 'Iniciar', você estará editando o mapa principal diretamente - as mudanças geralmente aparecem toda quinta-feira. Se você clicar em 'Play', as suas mudanças não serão salvas, de forma que você pode praticar a edição.\n\nLembre-se das regras de ouro do OpenStreetMap:\n\n"
"prompt_dontcopy": Não copie de outros mapas
"prompt_accuracy": Precisão é importante - apenas coloque mapas de onde você já esteve
"prompt_enjoy": E divirta-se!
"dontshowagain": Não mostre esta mensagem novamente
"prompt_start": Comece a mapear com o OpenStreetMap.
"prompt_practise": Pratique o mapeamento - suas alterações não serão salvas.
"practicemode": Modo de prática
"help": Ajuda
"prompt_help": Descubra como utilizar o Potlatch, este editor de mapas.
"track": Trilha
"prompt_track": Converta a sua trilha GPS para caminhos (trancados) a serem editados.
"action_deletepoint": Apagando um ponto
"deleting": Apagando
"action_cancelchanges": Cancelando as mudanças de
"emailauthor": \n\nFavor enviar um e-mail a richard\@systemeD.net com um relatório de erro, informando o que você estava fazendo na hora.
"error_connectionfailed": Sinto muito - a conexão ao servidor do OpenStreetMap falhou. Algumas alterações recentes não foram salvas.\n\nVocê gostaria de tentar novamente?
"option_background": "Plano de fundo:"
"option_fadebackground": Esmaecer o plano de fundo
"option_thinlines": Utilize linhas finas em todas as escalas
"option_custompointers": Utilize os apontadores caneta e mão
"tip_presettype": Escolha quais tipos predefinidos são oferecidos neste menu.
"action_waytags": Ajustando tags (rótulos) em um caminho
"action_pointtags": Ajustando tags (rótulos) em um ponto
"action_poitags": Ajustando tags (rótulos) em um ponto de interesse (POI)
"action_addpoint": Adicionando um nó ao fim do caminho
"add": Adicionar
"prompt_addtorelation": Adicionar $1 a uma relação
"prompt_selectrelation": Selecionar uma relação existente para adicionar a, ou criar, uma nova relação
"createrelation": Criar uma nova relação
"tip_selectrelation": Adicionar à rota escolhida
"action_reverseway": Invertendo um caminho
"tip_undo": Desfazer $1 (Z)
"error_noway": Caminho $1 não foi encontrado (talvez você mudou a sua posição?), por isso não posso desfazer.
"error_nosharedpoint": Caminhos $1 e $2 não compartilham mais um mesmo ponto, então a divisão não pode ser desfeita.
"error_nopoi": O ponto de interesse (POI) não foi encontrado (talvez você tenha mudado a sua posição?), por isso não posso desfazer.
"prompt_taggedpoints": Alguns dos pontos nesse caminho possuem tags (rótulos). Deseja realmente apagá-los?
"action_insertnode": Adicionando um nó em um caminho
"action_splitway": Dividindo um caminho
"editingmap": Editar o mapa
"start": Iniciar
"play": Praticar
"delete": Apagar
"a_way": $1 um caminho
"a_poi": $1 um ponto de interesse (POI)
"action_moveway": Movendo um caminho
"way": Caminho
"point": Ponto
