standard_settings: &standard_settings
  # The maximum area you're allowed to request, in square degrees
  max_request_area: 0.25
  # Number of GPS trace/trackpoints returned per-page
  tracepoints_per_page: 5000
  # Maximum number of nodes that will be returned by the api in a map request
  max_number_of_nodes: 50000
  # Maximum number of nodes that can be in a way (checked on save)
  max_number_of_way_nodes: 2000
  # Zoom level to use for postcode results from the geocoder
  postcode_zoom: 15
  # Zoom level to use for geonames results from the geocoder
  geonames_zoom: 12
 
development:
  <<: *standard_settings

production:
  <<: *standard_settings

test:
  <<: *standard_settings
