standard_settings: &standard_settings
  # The maximum area you're allowed to request, in square degrees
  max_request_area: 0.25
  # Number of GPS trace/trackpoints returned per-page
  tracepoints_per_page: 5000
  # Maximum number of nodes that will be returned by the api in a map request
  max_number_of_nodes: 50000
  # Maximum number of nodes that can be in a way (checked on save)
  max_number_of_way_nodes: 2000
  # Zoom level to use for postcode results from the geocoder
  postcode_zoom: 15
  # Zoom level to use for geonames results from the geocoder
  geonames_zoom: 12
  # Enable experimental "twain" geocoder
  twain_enabled: false
  # Timeout for API calls in seconds
  api_timeout: 300
  # Periods (in hours) which are allowed for user blocks
  user_block_periods: [0, 1, 3, 6, 12, 24, 48, 96]
  # Rate limit for message sending
  max_messages_per_hour: 60
 
development:
  <<: *standard_settings

production:
  <<: *standard_settings

test:
  <<: *standard_settings
