donate_2023:
  id: donate_2023
  alt: OpenStreetMap Funding Drive 2023
  link: https://supporting.openstreetmap.org/
  img: banners/donate_2023_1.jpg
  srcset:
    - [banners/donate_2023_1.jpg, 1x]
    - [banners/donate_2023_1@2x.jpg, 2x]
  dark: true
  enddate: 2023-dec-31
sotmeu_2024:
  id: sotmeu_2024
  alt: State of the Map Europe 2024
  link: https://tobilet.pl/state-of-the-map-europe-2024.html
  img: banners/StateoftheMapEurope_2024.png
  enddate: 2024-jul-18
sotmasia_2023:
  id: sotmasia_2023
  alt: State of the Map Asia x Foss4G Thailand 2023
  link: https://stateofthemap.asia/
  img: banners/SOTMAsia_x_FOSS4G_2023.jpg
  startdate: 2023-oct-18
  enddate: 2023-nov-18
sotmafrica_2023:
  id: sotmafrica_2023
  alt: State of the Map Africa 2023
  link: https://2023.stateofthemap.africa
  img: banners/StateOfTheMapAfrica_2023.jpg
  srcset:
    - [banners/StateOfTheMapAfrica_2023.jpg, 1x]
    - [banners/StateOfTheMapAfrica_2023@2x.jpg, 2x]
  startdate: 2023-oct-30
  enddate: 2023-nov-30
