fossgis2018:
  id: fossgis2018
  alt: FOSSGIS Conference 2018
  link: https://fossgis-konferenz.de/2018/
  img: banners/fossgis2018.png
  enddate: 2018-mar-24
sotmasia2017:
  id: sotmasia2017
  alt: State of the Map Asia 2017
  link: http://stateofthemap.asia/
  img: banners/sotmasia-2017-banner.png
  enddate: 2017-sep-25
sotmus2017:
  id: sotmus2017
  alt: State of the Map US 2017
  link: https://2017.stateofthemap.us/
  img: banners/banner-sotmus2017.png
  enddate: 2017-oct-20
osmfmembership2017:
  id: osmfmembership2017
  alt: Join the OpenStreetMap Foundation
  link: https://blog.openstreetmap.org/2017/09/25/join-the-openstreetmap-foundation-now-and-help-shape-the-future-of-the-project/
  img: banners/osmf-membership-drive-2017.png
  enddate: 2017-nov-11
