sotm_africa_2025:
  id: sotm_africa_2025
  alt: State of the Map Africa 2025
  link: https://2025.stateofthemap.africa
  img: banners/sotm_africa_2025.png
  srcset:
    - [banners/sotm_africa_2025.png, 1x]
  startdate: 2025-oct-31
  enddate: 2025-nov-28
