fossgis2018:
  id: fossgis2018
  alt: FOSSGIS Conference 2018
  link: https://fossgis-konferenz.de/2018/
  img: banners/fossgis2018.png
  enddate: 2018-mar-24
osmit2018:
  id: osmit2018
  alt: FOSS4G-IT 2018
  link: http://foss4g-it2018.gfoss.it/
  img: banners/foss4g-it2018-banner.png
  enddate: 2018-feb-22
sotm2018:
  id: sotm2018
  alt: SotM 2018
  link: https://2018.stateofthemap.org/
  img: banners/sotm2018.png
  enddate: 2018-jul-30
