donate_2023:
  id: donate_2023
  alt: OpenStreetMap Funding Drive 2023
  link: https://supporting.openstreetmap.org/
  img: banners/donate_2023_1.jpg
  srcset:
    - [banners/donate_2023_1.jpg, 1x]
    - [banners/donate_2023_1@2x.jpg, 2x]
  dark: true
  enddate: 2023-dec-31
sotmeu_2023:
  id: sotmeu_2023
  alt: State of the Map Europe 2023
  link: https://stateofthemap.eu/
  img: banners/StateoftheMapEurope_2023.png
  startdate: 2023-oct-05
  enddate: 2023-nov-05
sotmasia_2023:
  id: sotmasia_2023
  alt: State of the Map Asia x Foss4G Thailand 2023
  link: https://stateofthemap.asia/
  img: banners/SOTMAsia_x_FOSS4G_2023.png
  startdate: 2023-oct-18
  enddate: 2023-nov-18