# browse: svg images only
advertising_column:
  fill: advertising
  image: amenity_advertising_column.svg
aeroway_aerodrome:
  fill: airtransport
  image: amenity_aerodrome.svg
aeroway_helipad:
  fill: airtransport
  image: amenity_helipad.svg
amenity_arts_centre:
  fill: culture
  image: amenity_arts_centre.svg
amenity_atm:
  fill: amenity-brown
  image: amenity_atm.svg
amenity_bank:
  fill: public-service
  image: amenity_bank.svg
amenity_bar:
  fill: gastronomy
  image: amenity_bar.svg
amenity_bbq:
  fill: amenity-brown
  image: amenity_bbq.svg
amenity_bench:
  fill: man-made
  image: amenity_bench.svg
amenity_bicycle_parking:
  fill: transportation
  image: amenity_bicycle_parking.svg
amenity_bicycle_rental:
  fill: transportation
  image: amenity_rental_bicycle.svg
amenity_bicycle_repair_station:
  fill: amenity-brown
  image: amenity_bicycle_repair_station.svg
amenity_biergarten:
  fill: gastronomy
  image: amenity_biergarten.svg
amenity_boat_rental:
  fill: transportation
  image: amenity_boat_rental.svg
amenity_bureau_de_change:
  fill: amenity-brown
  image: amenity_bureau_de_change.svg
amenity_bus_station:
  image: amenity_bus_station.svg
amenity_cafe:
  fill: gastronomy
  image: amenity_cafe.svg
amenity_car_rental:
  fill: transportation
  image: amenity_rental_car.svg
amenity_car_sharing:
  fill: transportation
  image: car_share.svg
amenity_car_wash:
  fill: amenity-brown
  image: amenity_car_wash.svg
amenity_casino:
  fill: amenity-brown
  image: amenity_casino.svg
amenity_charging_station:
  fill: transportation
  image: amenity_charging_station.svg
amenity_childcare:
  fill: education
  image: amenity_childcare.svg
amenity_cinema:
  fill: culture
  image: amenity_cinema.svg
amenity_clinic:
  fill: health
  image: amenity_doctors.svg
amenity_community_centre:
  fill: culture
  image: amenity_community_centre.svg
amenity_courthouse:
  fill: public-service
  image: amenity_courthouse.svg
amenity_dentist:
  fill: health
  image: amenity_dentist.svg
amenity_doctors:
  fill: health
  image: amenity_doctors.svg
amenity_drinking_water:
  fill: amenity-brown
  image: amenity_drinking_water.svg
amenity_entrance:
  fill: amenity-brown
  image: amenity_entrance.svg
amenity_fast_food:
  fill: gastronomy
  image: amenity_fast_food.svg
amenity_ferry_terminal:
  fill: airtransport
  image: amenity_ferry.svg
amenity_fire_station:
  fill: public-service
  image: amenity_firestation.svg
amenity_fountain:
  fill: water
  image: amenity_fountain.svg
amenity_fuel:
  fill: transportation
  image: amenity_fuel.svg
amenity_helipad:
  fill: airtransport
  image: amenity_helipad.svg
amenity_hospital:
  fill: health
  image: amenity_hospital.svg
amenity_hunting_stand:
  fill: amenity-brown
  image: amenity_hunting_stand.svg
amenity_ice_cream:
  fill: gastronomy
  image: amenity_ice_cream.svg
amenity_internet_cafe:
  fill: amenity-brown
  image: amenity_internet_cafe.svg
amenity_kindergarten:
  fill: education
  image: amenity_childcare.svg
amenity_library:
  fill: culture
  image: amenity_library.svg
amenity_marketplace:
  fill: shop
  image: shop_marketplace.svg
amenity_motorcycle_parking:
  fill: transportation
  image: amenity_motorcycle_parking.svg
amenity_nightclub:
  fill: amenity-brown
  image: amenity_nightclub.svg
amenity_parcel_locker:
  fill: amenity-brown
  image: amenity_parcel_locker.svg
amenity_parking:
  fill: transportation
  image: amenity_parking.svg
amenity_parking_tickets:
  fill: amenity-brown
  image: amenity_parking_tickets.svg
amenity_pharmacy:
  fill: health
  image: amenity_pharmacy.svg
amenity_place_of_worship:
  fill: religious
  image: amenity_place_of_worship.svg
amenity_police:
  fill: public-service
  image: amenity_police.svg
amenity_post_box:
  fill: amenity-brown
  image: amenity_post_box.svg
amenity_post_office:
  fill: public-service
  image: amenity_post_office.svg
amenity_prison:
  fill: public-service
  image: amenity_prison.svg
amenity_pub:
  fill: gastronomy
  image: amenity_pub.svg
amenity_public_bath:
  fill: amenity-brown
  image: amenity_public_bath.svg
amenity_public_bookcase:
  fill: amenity-brown
  image: amenity_public_bookcase.svg
amenity_public_transport_tickets:
  fill: amenity-brown
  image: amenity_public_transport_tickets.svg
amenity_recycling:
  fill: amenity-brown
  image: amenity_recycling.svg
amenity_restaurant:
  fill: gastronomy
  image: amenity_restaurant.svg
amenity_school:
  fill: education
  image: education_school.svg
amenity_shelter:
  fill: accommodation
  image: amenity_shelter.svg
amenity_shower:
  fill: amenity-brown
  image: amenity_shower.svg
amenity_social_facility:
  fill: public-service
  image: amenity_social_facility.svg
amenity_taxi:
  fill: transportation
  image: amenity_taxi.svg
amenity_telephone:
  fill: amenity-brown
  image: amenity_telephone.svg
amenity_theatre:
  fill: culture
  image: amenity_theatre.svg
amenity_toilets:
  fill: amenity-brown
  image: amenity_toilets.svg
amenity_town_hall:
  fill: public-service
  image: amenity_town_hall.svg
amenity_townhall:
  fill: public-service
  image: amenity_town_hall.svg
amenity_vehicle_inspection:
  fill: public-service
  image: amenity_vehicle_inspection.svg
amenity_veterinary:
  fill: health
  image: amenity_veterinary.svg
amenity_waste_basket:
  class: amenity_waste_basket
  fill: amenity-brown
  image: amenity_waste_basket.svg
amenity_waste_disposal:
  fill: amenity-brown
  image: amenity_waste_disposal.svg
barrier_cattle_grid:
  fill: barrier
  image: barrier_cattle_grid.svg
barrier_cycle_barrier:
  fill: barrier
  image: barrier_cycle_barrier.svg
barrier_full-height_turnstile:
  fill: barrier
  image: barrier_full-height_turnstile.svg
barrier_gate:
  class: barrier_gate
  fill: barrier
  image: barrier_gate.svg
barrier_kissing_gate:
  fill: barrier
  image: barrier_kissing_gate.svg
barrier_lift_gate:
  class: barrier_gate
  fill: barrier
  image: barrier_lift_gate.svg
barrier_motorcycle_barrier:
  fill: barrier
  image: barrier_motorcycle_barrier.svg
barrier_stile:
  class: barrier_stile
  fill: barrier
  image: barrier_stile.svg
barrier_swing_gate:
  class: barrier_swing_gate
  fill: barrier
  image: barrier_lift_gate.svg
barrier_toll_booth:
  fill: transportation
  image: barrier_toll_booth.svg
emergency_phone:
  fill: amenity-brown
  image: amenity_emergency_phone.svg
highway_bus_stop:
  fill: transportation
  image: highway_bus_stop.svg
highway_elevator:
  fill: transportation
  image: highway_elevator.svg
highway_ford:
  fill: transportation
  image: highway_ford.svg
highway_mini_roundabout:
  fill: turning_circle
  image: highway_mini_roundabout.svg
highway_traffic_signals:
  class: highway_traffic_light
  fill: traffic-light
  image: highway_traffic_light.svg
highway_turning_circle:
  fill: turning_circle
  image: turning_circle.svg
historic_archaeological_site:
  fill: memorials
  image: historic_archaeological_site.svg
historic_castle:
  fill: memorials
  image: historic_castle.svg
historic_city_gate:
  fill: man-made
  image: historic_city_gate.svg
historic_fort:
  fill: memorials
  image: historic_fort.svg
historic_memorial:
  fill: memorials
  image: historic_memorial.svg
historic_monument:
  fill: memorials
  image: historic_monument.svg
leisure_amusement_arcade:
  fill: leisure
  image: leisure_amusement_arcade.svg
leisure_beach_resort:
  fill: leisure
  image: leisure_beach_resort.svg
leisure_bird_hide:
  fill: leisure
  image: leisure_bird_hide.svg
leisure_bowling_alley:
  fill: leisure
  image: leisure_bowling_alley.svg
leisure_dog_park:
  fill: leisure
  image: shop_pet.svg
leisure_firepit:
  fill: amenity-brown
  image: leisure_firepit.svg
leisure_fishing:
  fill: leisure
  image: leisure_fishing.svg
leisure_fitness_centre:
  fill: leisure
  image: leisure_fitness.svg
leisure_fitness_station:
  fill: leisure
  image: leisure_fitness.svg
leisure_golf_course:
  fill: leisure
  image: leisure_golf.svg
leisure_miniature_golf:
  fill: leisure
  image: leisure_miniature_golf.svg
leisure_outdoor_seating:
  fill: leisure
  image: leisure_outdoor_seating.svg
leisure_picnic_table:
  fill: man-made
  image: tourism_picnic.svg
leisure_playground:
  fill: leisure
  image: leisure_playground.svg
leisure_sauna:
  fill: leisure
  image: leisure_sauna.svg
leisure_slipway:
  fill: transportation
  image: leisure_slipway.svg
leisure_swimming_area:
  fill: leisure
  image: leisure_water_park.svg
leisure_water_park:
  fill: leisure
  image: leisure_water_park.svg
man_made_chimney:
  fill: man-made
  image: man_made_chimney.svg
man_made_communications_tower:
  fill: man-made
  image: man_made_communications_tower.svg
man_made_crane:
  fill: man-made
  image: man_made_crane.svg
man_made_cross:
  class: man_made_cross
  fill: religious
  image: man_made_cross.svg
man_made_lighthouse:
  fill: man-made
  image: man_made_lighthouse.svg
man_made_obelisk:
  fill: memorials
  image: historic_obelisk.svg
man_made_silo:
  fill: man-made
  image: man_made_storage_tank.svg
man_made_storage_tank:
  fill: man-made
  image: man_made_storage_tank.svg
man_made_water_tower:
  fill: man-made
  image: man_made_water_tower.svg
man_made_windmill:
  fill: man-made
  image: man_made_windmill.svg
natural_cave_entrance:
  image: natural_cave.svg
natural_peak:
  class: natural_saddle
  fill: landform
  image: natural_peak.svg
natural_saddle:
  class: natural_saddle
  fill: landform
  image: natural_saddle.svg
natural_tree:
  fill: tree
  image: natural_tree.svg
office_diplomatic:
  fill: office
  image: office_embassy.svg
railway_halt:
  fill: railway
  image: railway_halt.svg
railway_level_crossing:
  fill: man-made
  image: barrier_level_crossing2.svg
railway_station:
  fill: railway
  image: railway_station.svg
shop:
  fill: shop
  image: shop_convenience.svg
shop_alcohol:
  fill: shop
  image: shop_alcohol.svg
shop_art:
  fill: shop
  image: shop_art.svg
shop_bag:
  fill: shop
  image: shop_bag.svg
shop_bakery:
  fill: shop
  image: shop_bakery.svg
shop_beauty:
  fill: shop
  image: shop_beauty.svg
shop_bed:
  fill: shop
  image: shop_bed.svg
shop_beverages:
  fill: shop
  image: shop_beverages.svg
shop_bicycle:
  fill: shop
  image: shop_bicycle.svg
shop_bookmaker:
  fill: shop
  image: shop_bookmaker.svg
shop_books:
  fill: shop
  image: amenity_library.svg
shop_butcher:
  fill: shop
  image: shop_butcher.svg
shop_car:
  fill: shop
  image: shop_car.svg
shop_car_parts:
  fill: shop
  image: shop_car_parts.svg
shop_car_repair:
  fill: shop
  image: shop_car_repair.svg
shop_carpet:
  fill: shop
  image: shop_carpet.svg
shop_charity:
  fill: shop
  image: shop_charity.svg
shop_chemist:
  fill: shop
  image: shop_chemist.svg
shop_chocolate:
  fill: shop
  image: shop_confectionery.svg
shop_clothes:
  fill: shop
  image: shop_clothes.svg
shop_coffee:
  fill: shop
  image: shop_coffee.svg
shop_computer:
  fill: shop
  image: shop_computer.svg
shop_confectionery:
  fill: shop
  image: shop_confectionery.svg
shop_convenience:
  fill: shop
  image: shop_convenience.svg
shop_copyshop:
  fill: shop
  image: shop_copyshop.svg
shop_cosmetics:
  fill: shop
  image: shop_perfumery.svg
shop_deli:
  fill: shop
  image: shop_deli.svg
shop_department_store:
  fill: shop
  image: shop_department_store.svg
shop_doityourself:
  fill: shop
  image: shop_diy.svg
shop_dry_cleaning:
  fill: shop
  image: shop_laundry.svg
shop_electronics:
  fill: shop
  image: shop_electronics.svg
shop_fabric:
  fill: shop
  image: shop_fabric.svg
shop_farm:
  fill: shop
  image: shop_greengrocer.svg
shop_fashion:
  fill: shop
  image: shop_clothes.svg
shop_fishmonger:
  fill: shop
  image: shop_seafood.svg
shop_florist:
  fill: shop
  image: shop_florist.svg
shop_furniture:
  fill: shop
  image: shop_furniture.svg
shop_garden_centre:
  fill: shop
  image: shop_garden_centre.svg
shop_gift:
  fill: shop
  image: shop_gift.svg
shop_greengrocer:
  fill: shop
  image: shop_greengrocer.svg
shop_hairdresser:
  fill: shop
  image: shop_hairdresser.svg
shop_hardware:
  fill: shop
  image: shop_diy.svg
shop_hearing_aids:
  fill: shop
  image: shop_hearing_aids.svg
shop_houseware:
  fill: shop
  image: shop_houseware.svg
shop_interior_decoration:
  fill: shop
  image: shop_interior_decoration.svg
shop_jewelry:
  fill: shop
  image: shop_jewelry.svg
shop_kiosk:
  fill: shop
  image: shop_newsagent.svg
shop_laundry:
  fill: shop
  image: shop_laundry.svg
shop_massage:
  fill: leisure
  image: shop_massage.svg
shop_medical_supply:
  fill: shop
  image: shop_medical_supply.svg
shop_mobile_phone:
  fill: shop
  image: shop_mobile_phone.svg
shop_motorcycle:
  fill: shop
  image: shop_motorcycle.svg
shop_music:
  fill: shop
  image: shop_music.svg
shop_musical_instrument:
  fill: shop
  image: shop_musical_instrument.svg
shop_newsagent:
  fill: shop
  image: shop_newsagent.svg
shop_optician:
  fill: shop
  image: shop_optician.svg
shop_paint:
  fill: shop
  image: shop_paint.svg
shop_pastry:
  fill: shop
  image: shop_confectionery.svg
shop_perfumery:
  fill: shop
  image: shop_perfumery.svg
shop_pet:
  fill: shop
  image: shop_pet.svg
shop_photo:
  fill: shop
  image: shop_photo.svg
shop_photo_studio:
  fill: shop
  image: shop_photo.svg
shop_photography:
  fill: shop
  image: shop_photo.svg
shop_seafood:
  fill: shop
  image: shop_seafood.svg
shop_second_hand:
  fill: shop
  image: shop_second_hand.svg
shop_shoes:
  fill: shop
  image: shop_shoes.svg
shop_sports:
  fill: shop
  image: shop_sports.svg
shop_stationery:
  fill: shop
  image: shop_stationery.svg
shop_supermarket:
  fill: shop
  image: shop_supermarket.svg
shop_tea:
  fill: shop
  image: shop_tea.svg
shop_ticket:
  fill: shop
  image: shop_ticket.svg
shop_tobacco:
  fill: shop
  image: shop_tobacco.svg
shop_toys:
  fill: shop
  image: shop_toys.svg
shop_trade:
  fill: shop
  image: shop_trade.svg
shop_travel_agency:
  fill: shop
  image: shop_travel_agency.svg
shop_tyres:
  fill: shop
  image: shop_tyres.svg
shop_variety_store:
  fill: shop
  image: shop_variety_store.svg
shop_video:
  fill: shop
  image: shop_video.svg
shop_video_games:
  fill: shop
  image: shop_video_games.svg
shop_wine:
  fill: shop
  image: shop_alcohol.svg
tourism_alpine_hut:
  fill: accommodation
  image: tourism_alpinehut.svg
tourism_apartment:
  fill: accommodation
  image: tourism_apartment.svg
tourism_artwork:
  fill: amenity-brown
  image: tourism_artwork.svg
tourism_camp_site:
  fill: accommodation
  image: tourism_camping.svg
tourism_caravan_site:
  fill: accommodation
  image: tourism_caravan_park.svg
tourism_chalet:
  fill: accommodation
  image: tourism_chalet.svg
tourism_gallery:
  fill: amenity-brown
  image: shop_art.svg
tourism_guest_house:
  fill: accommodation
  image: tourism_guest_house.svg
tourism_hostel:
  fill: accommodation
  image: tourism_hostel.svg
tourism_hotel:
  fill: accommodation
  image: tourism_hotel.svg
tourism_motel:
  fill: accommodation
  image: tourism_motel.svg
tourism_museum:
  fill: culture
  image: tourism_museum.svg
tourism_picnic_site:
  fill: leisure
  image: tourism_picnic.svg
tourism_picnic_table:
  fill: leisure
  image: tourism_picnic.svg
tourism_viewpoint:
  fill: amenity-brown
  image: tourism_viewpoint.svg
tourism_wilderness_hut:
  fill: accommodation
  image: tourism_wilderness_hut.svg
