aeroway:
  aerodrome: { filename: "aerodrome.p.16.png" }

  runway: { filename: "runway.20.png" }
  taxiway: { filename: "taxiway.20.png" }

amenity:
  atm: { filename: "amenity_atm.16.png", invert: true }
  bank: { filename: "amenity_bank.16.png", invert: true }
  bar: { filename: "amenity_bar.16.png", invert: true }
  bench: { filename: "amenity_bench.16.png", invert: true }
  biergarten: { filename: "amenity_biergarten.16.png", invert: true }
  bicycle_parking: { filename: "amenity_bicycle_parking.16.png" }
  bicycle_rental: { filename: "transport_rental_bicycle.16.png" }
  bus_station: { filename: "bus_station.n.16.png" }
  cafe: { filename: "amenity_cafe.16.png", invert: true }
  car_rental: { filename: "transport_rental_car.16.png" }
  car_sharing: { filename: "car_share.p.16.png" }
  childcare: { filename: "amenity_childcare.p.16.png" }
  cinema: { filename: "amenity_cinema.16.png", invert: true }
  courthouse: { filename: "amenity_courthouse.16.png", invert: true }
  dentist: { filename: "amenity_dentist.16.png" }
  doctors: { filename: "amenity_doctors.16.png" }
  drinking_water: { filename: "amenity_drinking_water.16.png", invert: true }
  fast_food: { filename: "amenity_fast_food.16.png", invert: true }
  fire_station: { filename: "amenity_fire_station.16.png", invert: true }
  fuel: { filename: "amenity_fuel.16.png" }
  hospital: { filename: "amenity_hospital.16.png" }
  kindergarten: { filename: "amenity_childcare.p.16.png" }
  library: { filename: "library.p.16.png", invert: true }
  nightclub: { filename: "amenity_nightclub.16.png", invert: true }
  parking: { filename: "parking.p.16.png" }
  pharmacy: { filename: "amenity_pharmacy.16.png" }
  place_of_worship: { filename: "amenity_place_of_worship.16.png", invert: true }
  police: { filename: "amenity_police.16.png", invert: true }
  post_box: { filename: "post_box.p.16.png", invert: true }
  post_office: { filename: "post_office.p.16.png", invert: true }
  prison: { filename: "amenity_prison.16.png", invert: true }
  pub: { filename: "amenity_pub.16.png", invert: true }
  restaurant: { filename: "amenity_restaurant.16.png", invert: true }
  recycling: { filename: "amenity_recycling.16.png", invert: true }
  school: { filename: "education_school.p.16.png" }
  shelter: { filename: "shelter2.p.16.png" }
  taxi: { filename: "amenity_taxi.16.png" }
  telephone: { filename: "telephone.p.16.png", invert: true }
  theatre: { filename: "amenity_theatre.16.png", invert: true }
  toilets: { filename: "amenity_toilets.16.png", invert: true }
  townhall: { filename: "amenity_townhall.16.png", invert: true }
  university: { filename: "education_university.p.16.png" }
  veterinary: { filename: "health_veterinary.p.16.png" }
  waste_basket: { filename: "amenity_waste_basket.16.png", invert: true }

barrier:
  gate: { filename: "gate2.p.16.png", invert: true }

  wall: { filename: "wall.20.png" }

building:
  :*: { filename: "building.png" }

highway:
  bus_stop: { filename: "highway_bus_stop.16.png" }
  mini_roundabout: { filename: "mini_round.p.16.png" }
  traffic_signals: { filename: "traffic_light.png", invert: true }
  turning_circle: { filename: "turning_circle.p.16.png" }

  bridleway: { filename: "bridleway.20.png" }
  cycleway: { filename: "cycleway.20.png" }
  footway: { filename: "footway.20.png" }
  motorway: { filename: "motorway.20.png" }
  motorway_link: { filename: "motorway.20.png" }
  path: { filename: "path.20.png" }
  pedestrian: { filename: "service.20.png" }
  primary: { filename: "primary.20.png" }
  primary_link: { filename: "primary.20.png" }
  residential: { filename: "unclassified.20.png" }
  secondary: { filename: "secondary.20.png" }
  secondary_link: { filename: "secondary.20.png" }
  service: { filename: "service.20.png" }
  tertiary: { filename: "tertiary.20.png" }
  track: { filename: "track.20.png" }
  trunk: { filename: "trunk.20.png" }
  trunk_link: { filename: "trunk.20.png" }
  unclassified: { filename: "unclassified.20.png" }

historic:
  archaeological_site: { filename: "historic_archaeological_site.16.png", invert: true }
  castle: { filename: "tourist_castle.p.16.png", invert: true }
  memorial: { filename: "historic_memorial.16.png", invert: true }
  monument: { filename: "historic_monument.16.png", invert: true }
  ruins: { filename: "tourist_ruins.p.16.png", invert: true }
  wreck: { filename: "tourist_wreck.p.16.png", invert: true }

landuse:
  brownfield: { filename: "brownfield.png" }
  cemetery: { filename: "cemetery.png" }
  commercial: { filename: "commercial.png" }
  farmland: { filename: "farmland.png" }
  farmyard: { filename: "farmyard.png" }
  forest: { filename: "forest.png" }
  grass: { filename: "grass.png" }
  industrial: { filename: "industrial.png" }
  meadow: { filename: "meadow.png" }
  military: { filename: "military.png" }
  residential: { filename: "residential.png" }
  retail: { filename: "retail.png" }
  tourism: { filename: "tourism.png" }

leisure:
  golf_course: { filename: "golf.png" }
  park: { filename: "park.png" }
  picnic_table: { filename: "tourism_picnic_site.16.png", invert: true }
  playground: { filename: "leisure_playground.16.png", invert: true }
  pitch: { filename: "pitch.png" }
  nature_reserve: { filename: "reserve.png" }
  water_park: { filename: "leisure_water_park.16.png", invert: true }

man_made:
  lighthouse: { filename: "man_made_lighthouse.16.png" }
  water_tower: { filename: "man_made_water_tower.16.png", invert: true }
  windmill: { filename: "man_made_windmill.16.png", invert: true }

natural:
  tree: { filename: "tree.p.16.png" }

  grassland: { filename: "grassland.png" }
  heath: { filename: "heathland.png" }
  scrub: { filename: "scrub.png" }
  water: { filename: "lake.png" }
  wood: { filename: "wood.png" }

office:
  diplomatic: { filename: "office_diplomatic.16.png" }
  estate_agent: { filename: "shop_estateagent.16.png" }

railway:
  halt: { filename: "halt.p.16.png" }
  station: { filename: "station.p.16.png" }
  level_crossing: { filename: "level_crossing.p.16.png", invert: true }

  light_rail: { filename: "light_rail.20.png" }
  rail: { filename: "rail.20.png" }
  subway: { filename: "subway.20.png" }
  tram: { filename: "tram.20.png" }

shop:
  :*: { filename: "shop_convenience.p.16.png", priority: 20 }
  alcohol: { filename: "shop_alcohol.16.png" }
  bakery: { filename: "shop_bakery.16.png" }
  bicycle: { filename: "shop_bicycle.16.png" }
  books: { filename: "shop_books.16.png" }
  butcher: { filename: "shop_butcher.p.16.png" }
  clothes: { filename: "shop_clothes.16.png" }
  car_parts: { filename: "shop_car_parts.16.png" }
  car_repair: { filename: "shop_car_repair.16.png" }
  convenience: { filename: "shop_convenience.p.16.png" }
  doityourself: { filename: "shop_doityourself.16.png" }
  electronics: { filename: "shop_electronics.16.png" }
  estate_agent: { filename: "shop_estateagent.16.png" }
  fashion: { filename: "shop_clothes.16.png" }
  florist: { filename: "shop_florist.16.png" }
  furniture: { filename: "shop_furniture.16.png" }
  garden_centre: { filename: "shop_florist.16.png" }
  gift: { filename: "shop_gift.16.png" }
  greengrocer: { filename: "shop_greengrocer.p.16.png" }
  hardware: { filename: "shop_doityourself.16.png" }
  hairdresser: { filename: "shop_hairdresser.16.png" }
  jewelry: { filename: "shop_jewelry.16.png" }
  mobile_phone: { filename: "shop_mobile_phone.16.png" }
  optician: { filename: "shop_optician.16.png" }
  pet: { filename: "shop_pet.16.png" }
  seafood: { filename: "shop_seafood.16.png" }
  shoes: { filename: "shop_shoes.16.png" }
  supermarket: { filename: "shop_supermarket.p.16.png" }

tourism:
  alpine_hut: { filename: "tourism_alpine_hut.16.png" }
  camp_site: { filename: "tourism_camp_site.16.png" }
  caravan_site: { filename: "tourism_caravan_site.16.png" }
  hostel: { filename: "tourism_hostel.16.png" }
  hotel: { filename: "tourism_hotel.16.png" }
  motel: { filename: "tourism_motel.16.png" }
  museum: { filename: "tourism_museum.16.png", invert: true }
  picnic_site: { filename: "tourism_picnic_site.16.png", invert: true }
  viewpoint: { filename: "view_point.p.16.png", invert: true }
  wilderness_hut: { filename: "tourism_wilderness_hut.16.png" }
