defaults: &defaults
  # The server protocol and host
  server_protocol: "http"
  server_url: "openstreetmap.example.com"
  # Publisher
  #publisher_url: ""
  # The generator
  generator: "OpenStreetMap server"
  copyright_owner: "OpenStreetMap and contributors"
  attribution_url: "http://www.openstreetmap.org/copyright"
  license_url: "http://opendatacommons.org/licenses/odbl/1-0/"
  # Support email address
  support_email: "openstreetmap@example.com"
  # Sender addresses for emails
  email_from: "OpenStreetMap <openstreetmap@example.com>"
  email_return_path: "openstreetmap@example.com"
  # API version
  api_version: "0.6"
  # Application status - possible values are:
  #   :online - online and operating normally
  #   :api_readonly - site online but API in read-only mode
  #   :api_offline - site online but API offline
  #   :database_readonly - database and site in read-only mode
  #   :database_offline - database offline with site in emergency mode
  #   :gpx_offline - gpx storage offline
  status: :online
  # The maximum area you're allowed to request, in square degrees
  max_request_area: 0.25
  # Number of GPS trace/trackpoints returned per-page
  tracepoints_per_page: 5000
  # Maximum number of nodes that will be returned by the api in a map request
  max_number_of_nodes: 50000
  # Maximum number of nodes that can be in a way (checked on save)
  max_number_of_way_nodes: 2000
  # The maximum area you're allowed to request notes from, in square degrees
  max_note_request_area: 25
  # Zoom level to use for postcode results from the geocoder
  postcode_zoom: 15
  # Zoom level to use for geonames results from the geocoder
  geonames_zoom: 12
  # Timeout for API calls in seconds
  api_timeout: 300
  # Timeout for web pages in seconds
  web_timeout: 30
  # Periods (in hours) which are allowed for user blocks
  user_block_periods: [0, 1, 3, 6, 12, 24, 48, 96]
  # Rate limit for message sending
  max_messages_per_hour: 60
  # Domain for handling message replies
  #messages_domain: "messages.openstreetmap.org"
  # Geonames authentication details
  #geonames_username: ""
  # GeoIP database
  #geoip_database: ""
  # Users to show as being nearby
  nearby_users: 30
  # Max radius, in km, for nearby users
  nearby_radius: 50
  # Spam threshold
  spam_threshold: 50
  # Default legale (jurisdiction location) for contributor terms
  default_legale: GB
  # Location of GPX traces and images
  gpx_trace_dir: "/home/osm/traces"
  gpx_image_dir: "/home/osm/images"
  # Location of data for attachments
  attachments_dir: ":rails_root/public/attachments"
  # Log file to use
  #log_path: ""
  # Log file to use for logstash
  #logstash_path: ""
  # List of memcache servers to use for caching
  #memcache_servers: []
  # Enable legacy OAuth 1.0 support
  oauth_10_support: true
  # URL of Nominatim instance to use for geocoding
  nominatim_url: "https://nominatim.openstreetmap.org/"
  # Default editor
  default_editor: "id"
  # OAuth consumer key for Potlatch 2
  #potlatch2_key: ""
  # OAuth consumer key for the web site
  #oauth_key: ""
  # OAuth consumer key for iD
  #id_key: ""
  # Whether to require users to view the CTs before continuing to edit...
  require_terms_seen: false
  # Whether to require users to agree to the CTs before editing
  require_terms_agreed: false
  # Imagery to return in capabilities as blacklisted
  imagery_blacklist:
    # Current Google imagery URLs have google or googleapis in the domain
    # with a vt or kh endpoint, and x, y and z query parameters
    - ".*\\.google(apis)?\\..*/(vt|kh)[\\?/].*([xyz]=.*){3}.*"
    # Blacklist VWorld
    - "http://xdworld\\.vworld\\.kr:8080/.*"
    # Blacklist here
    - ".*\\.here\\.com[/:].*"
  # URL of Overpass instance to use for feature queries
  overpass_url: "//overpass-api.de/api/interpreter"
  # Routing endpoints
  graphhopper_url: "//graphhopper.com/api/1/route"
  mapquest_directions_url: "//open.mapquestapi.com/directions/v2/route"
  osrm_url: "//router.project-osrm.org/route/v1/driving/"
  # External authentication credentials
  #google_auth_id: ""
  #google_auth_secret: ""
  #google_openid_realm: ""
  #facebook_auth_id: ""
  #facebook_auth_secret: ""
  #windowslive_auth_id: ""
  #windowslive_auth_secret: ""
  #github_auth_id: ""
  #github_auth_secret: ""
  #wikipedia_auth_id: ""
  #wikipedia_auth_secret: ""
  # MapQuest authentication details
  #mapquest_key: ""
  # Thunderforest authentication details
  #thunderforest_key: ""
  # Key for generating TOTP tokens
  #totp_key: ""
  # URL for reporting Content-Security-Policy violations
  #csp_report_url: ""

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
  # Geonames credentials for testing
  geonames_username: "dummy"
  # External authentication credentials for testing
  google_auth_id: "dummy"
  google_auth_secret: "dummy"
  google_openid_realm: "https://www.openstreetmap.org"
  facebook_auth_id: "dummy"
  facebook_auth_secret: "dummy"
  windowslive_auth_id: "dummy"
  windowslive_auth_secret: "dummy"
  github_auth_id: "dummy"
  github_auth_secret: "dummy"
  wikipedia_auth_id: "dummy"
  wikipedia_auth_secret: "dummy"
