# Local overrides and secrets
# These settings are for local, Docker-based development
# OAuth keys are generated at installation time; see CONFIGURE.md
server_url: "0.0.0.0:3000" 
api_timeout: 600
web_timeout: 600
# OAuth application for the web site
oauth_application: ""
oauth_key: ""
# OAuth consumer key for iD
id_application: ""
