standard_settings: &standard_settings
  # The server URL
  server_url: "www.openstreetmap.org"
  # The generator
  generator: "OpenStreetMap server"
  # Sender addresses for emails
  email_from: "OpenStreetMap <webmaster@openstreetmap.org>"
  email_return_path: "bounces@openstreetmap.org"
  # API version
  api_version: "0.6"
  # Application status - posstible values are:
  #   :online - online and operating normally
  #   :api_readonly - site online but API in read-only mode
  #   :api_offline - site online but API offline
  #   :database_readonly - database and site in read-only mode
  #   :database_offline - database offline with site in emergency mode
  #   :gpx_offline - gpx storage offline
  status: :online
  # The maximum area you're allowed to request, in square degrees
  max_request_area: 0.25
  # Number of GPS trace/trackpoints returned per-page
  tracepoints_per_page: 5000
  # Maximum number of nodes that will be returned by the api in a map request
  max_number_of_nodes: 50000
  # Maximum number of nodes that can be in a way (checked on save)
  max_number_of_way_nodes: 2000
  # Zoom level to use for postcode results from the geocoder
  postcode_zoom: 15
  # Zoom level to use for geonames results from the geocoder
  geonames_zoom: 12
  # Timeout for API calls in seconds
  api_timeout: 300
  # Timeout for web pages in seconds
  web_timeout: 30
  # Periods (in hours) which are allowed for user blocks
  user_block_periods: [0, 1, 3, 6, 12, 24, 48, 96]
  # Rate limit for message sending
  max_messages_per_hour: 60
  # Domain for handling message replies
  #messages_domain: "messages.openstreetmap.org"
  # Quova authentication details
  #quova_username: ""
  #quova_password: ""
  # Users to show as being nearby
  nearby_users: 30
  # Max radius, in km, for nearby users
  nearby_radius: 50
  # Spam threshold
  spam_threshold: 50
  # Default legale (jurisdiction location) for contributor terms
  default_legale: GB
  # Memory limits (in Mb)
  #soft_memory_limit: 512
  #hard_memory_limit: 2048
  # Location of GPX traces and images
  gpx_trace_dir: "/home/osm/traces"
  gpx_image_dir: "/home/osm/images"
  # Location of data for file columns
  #file_column_root: ""
  # Enable legacy OAuth 1.0 support
  oauth_10_support: true
  # URL of Nominatim instance to use for geocoding
  nominatim_url: "http://nominatim.openstreetmap.org/"
  # Default editor
  default_editor: "potlatch"
  # OAuth consumer key for Potlatch 2
  #potlatch2_key: ""

development:
  <<: *standard_settings

production:
  <<: *standard_settings

test:
  <<: *standard_settings
