# OHM overrides and secrets
# These settings are for local, Docker-based development
# OAuth keys are generated at installation time; see CONFIGURE.md
server_url: "0.0.0.0:3000"
embed_server_url: "https://embed.openhistoricalmap.org/"
generator: "OpenHistoricalMap server"
copyright_owner: "OpenHistoricalMap and contributors"
attribution_url: "http://www.openhistoricalmap.org/copyright"
support_email: "ohm-admins@googlegroups.com"
email_from: "OpenHistoricalMap <ohm-admins@googlegroups.com>"
email_return_path: "ohm-admins@googlegroups.com"
max_number_of_nodes: 100000
api_timeout: 600
web_timeout: 600
#memcache_servers: []
nominatim_url: "https://nominatim.openhistoricalmap.org/"
# OAuth application for the website
oauth_application: ""
oauth_key: ""
# OAuth consumer key for iD
id_application: ""
imagery_blacklist:
  # Current Google imagery URLs have google or googleapis in the domain
  - ".*\\.google(apis)?\\..*/.*"
  # Blacklist VWorld
  - "http://xdworld\\.vworld\\.kr:8080/.*"
  # Blacklist here
  - ".*\\.here\\.com[/:].*"
overpass_url: "https://overpass-api.openhistoricalmap.org/api/interpreter"
# Mastodon url for verification
mastodon_url: "https://mapstodon.space/@ohm"
