embed_fallback_translations:
  enabled: true
export_files:
  enabled: true
  files:
    - template: "i18n/templates/template.js.erb"
      output: "app/assets/javascripts/i18n/%{base_name}.js"
translations:
  - file: "i18n/data/:locale.json"
    patterns:
    - "*.date.*"
    - "*.time.*"
    - "*.browse.start_rjs.*"
    - "*.javascripts.*"
    - "*.site.edit.*"
    - "*.site.index.remote_failed"
    - "*.site.sidebar.search_results"
    - "*.diary_entries.edit.marker_text"
    - "*.layouts.project_name.title"
    - "*.geocoder.search_osm_nominatim.*"
  - file: "i18n/data/embed.json"
    patterns:
    - "*.javascripts.embed.*"
