skip_missing_workers: true
pngout: false
pngcrush: false
advpng: false
optipng: false
pngquant: false
jhead: false
jpegoptim: false
gifsicle: false
jpegtran: false
svgo:
  disable_plugins: ["cleanupIDs", "removeUselessStrokeAndFill"]
