files:
  - "**/*.js"
exclude_paths:
  - "app/assets/javascripts/i18n"
  - "vendor/assets/javascripts"
options:
  eqeqeq: true
  freeze: true
  latedef: "nofunc"
  noarg: true
  noempty: true
  nonew: true
  undef: true
  browser: true
  jquery: true
  unused: true
  trailing: true
  globals:
    I18n: false
    L: true
    OSM: true
    Piwik: false
    alert: false
    escape: false
    maximiseMap: false
    minimiseMap: false
    querystring: true
    require: false
    updateLinks: false
    bowser: false
