mapnik:
  # transportation
  - { min_zoom: 6, max_zoom: 19, name: motorway, image: motorway.png }
  - { min_zoom: 6, max_zoom: 7, name: main_road, image: mainroad.png }
  - { min_zoom: 8, max_zoom: 11, name: main_road, image: mainroad8.png }
  - { min_zoom: 12, max_zoom: 19, name: main_road, image: mainroad12.png }
  - { min_zoom: 13, max_zoom: 19, name: track, image: track.png }
  - { min_zoom: 13, max_zoom: 19, name: bridleway, image: bridleway.png }
  - { min_zoom: 13, max_zoom: 19, name: cycleway, image: cycleway.png }
  - { min_zoom: 13, max_zoom: 19, name: footway, image: footway.png }
  - { min_zoom: 8, max_zoom: 11, name: rail, image: rail.png }
  - { min_zoom: 12, max_zoom: 19, name: rail, image: rail12.png }
  - { min_zoom: 13, max_zoom: 19, name: subway, image: subway.png }
  - { min_zoom: 13, max_zoom: 19, name: tram, image: tram.png }
  - { min_zoom: 12, max_zoom: 19, name: cable, image: cable.png }
  - { min_zoom: 11, max_zoom: 19, name: runway, image: runway.png }
  - { min_zoom: 12, max_zoom: 19, name: apron, image: apron.png }
  # administrative boundaries: admin.mss
  - { name: admin, width: 52, height: 2, fill: "#8d618b88" }
  # landcover z5: landcover.mss, water.mss
  - { name: lake, width: 26, height: 10, fill: "#aad3df" }
  - { min_zoom: 5, max_zoom: 9, name: glacier, image: glacier5.svg }
  - { min_zoom: 10, name: glacier, image: glacier10.svg }
  - { min_zoom: 5, max_zoom: 11, name: forest, width: 26, height: 10, fill: "#bddab1" }
  - { min_zoom: 12, name: forest, width: 26, height: 10, fill: "#add19e" }
  - { min_zoom: 5, max_zoom: 11, name: orchard, width: 26, height: 10, fill: "#bee5b5" }
  - { min_zoom: 12, name: orchard, width: 26, height: 10, fill: "#aedfa3" }
  - { min_zoom: 5, max_zoom: 11, name: grass, width: 26, height: 10, fill: "#d7efc0" }
  - { min_zoom: 12, name: grass, width: 26, height: 10, fill: "#cdebb0" }
  - { min_zoom: 5, max_zoom: 11, name: farmland, width: 26, height: 10, fill: "#f1f3dd" }
  - { min_zoom: 12, name: farmland, width: 26, height: 10, fill: "#eef0d5" }
  - { min_zoom: 5, max_zoom: 11, name: heathland, width: 26, height: 10, fill: "#dee1b2" }
  - { min_zoom: 12, name: heathland, width: 26, height: 10, fill: "#d6d99f" }
  - { min_zoom: 5, max_zoom: 11, name: scrubland, width: 26, height: 10, fill: "#d3dfbc" }
  - { min_zoom: 12, name: scrubland, width: 26, height: 10, fill: "#c8d7ab" }
  - { min_zoom: 5, max_zoom: 11, name: bare_rock, width: 26, height: 10, fill: "#f1eae3" }
  - { min_zoom: 12, name: bare_rock, width: 26, height: 10, fill: "#eee5dc" }
  - { min_zoom: 5, max_zoom: 11, name: sand, width: 26, height: 10, fill: "#f7edd1" }
  - { min_zoom: 12, name: sand, width: 26, height: 10, fill: "#f5e9c6" }
  # landuse z8, z10: landcover.mss
  - { min_zoom: 10, name: park, width: 26, height: 10, fill: "#c8facc" }
  - { min_zoom: 10, name: golf, width: 26, height: 10, fill: "#def6c0" }
  - { min_zoom: 8, max_zoom: 11, name: built_up, width: 26, height: 10, fill: "#d9d9d9" }
  - { min_zoom: 12, max_zoom: 12, name: built_up, width: 26, height: 10, fill: "#dddddd" }
  - { min_zoom: 13, name: resident, width: 26, height: 10, fill: "#e0dfdf" }
  - { min_zoom: 13, name: retail, width: 26, height: 10, fill: "#ffd6d1" }
  - { min_zoom: 13, name: commercial, width: 26, height: 10, fill: "#f2dad9" }
  - { min_zoom: 13, name: industrial, width: 26, height: 10, fill: "#ebdbe8" }
  - { min_zoom: 10, max_zoom: 11, name: farm, width: 26, height: 10, fill: "#f7e3c8" }
  - { min_zoom: 12, name: farm, width: 26, height: 10, fill: "#f5dcba" }
  - { min_zoom: 10, max_zoom: 11, name: brownfield, width: 26, height: 10, fill: "#d2d2c3" }
  - { min_zoom: 12, name: brownfield, width: 26, height: 10, fill: "#c7c7b4" }
  - { min_zoom: 10, max_zoom: 11, name: cemetery, width: 26, height: 10, fill: "#bbd5be" }
  - { min_zoom: 12, name: cemetery, width: 26, height: 10, fill: "#aacbaf" }
  - { min_zoom: 10, max_zoom: 11, name: allotments, width: 26, height: 10, fill: "#d4e6cc" }
  - { min_zoom: 12, name: allotments, width: 26, height: 10, fill: "#c9e1bf" }
  - { min_zoom: 11, name: pitch, width: 26, height: 10, fill: "#88e0be" }
  - { min_zoom: 11, name: centre, width: 26, height: 10, fill: "#dffce2" }
  - { min_zoom: 10, name: reserve, image: reserve.svg } # admin.mss
  - { min_zoom: 8, name: military, image: military.svg }
  - { min_zoom: 13, name: school, image: school.svg }
  # buildings: buildings.mss
  - { min_zoom: 14, name: building, width: 10, height: 10, fill: "#ab9793" }
  - { min_zoom: 15, name: building, image: building15.svg }
  - { min_zoom: 16, name: building, image: building16.svg }
  # stations: stations.mss
  - { min_zoom: 12, name: station, width: 4, height: 4, fill: "#7981b0" }
  - { min_zoom: 13, name: station, width: 6, height: 6, fill: "#7981b0" }
  - { min_zoom: 15, name: station, width: 9, height: 9, fill: "#7981b0" }
  # other
  - { min_zoom: 11, max_zoom: 19, name: summit, image: summit.png }
  - { min_zoom: 12, max_zoom: 19, name: tunnel, image: tunnel.png }
  - { min_zoom: 13, max_zoom: 19, name: bridge, image: bridge.png }
  - { min_zoom: 15, max_zoom: 19, name: private, image: private.png }
  - { min_zoom: 15, max_zoom: 19, name: destination, image: destination.png }
  - { min_zoom: 12, max_zoom: 19, name: construction, image: construction.png }
cyclemap:
  - { min_zoom: 0, max_zoom: 11, name: motorway, image: motorway.png }
  - { min_zoom: 12, max_zoom: 19, name: motorway, image: motorway12.png }
  - { min_zoom: 0, max_zoom: 11, name: trunk, image: trunk.png }
  - { min_zoom: 12, max_zoom: 19, name: trunk, image: trunk12.png }
  - { min_zoom: 7, max_zoom: 11, name: primary, image: primary.png }
  - { min_zoom: 12, max_zoom: 19, name: primary, image: primary12.png }
  - { min_zoom: 9, max_zoom: 11, name: secondary, image: secondary.png }
  - { min_zoom: 12, max_zoom: 19, name: secondary, image: secondary12.png }
  - { min_zoom: 13, max_zoom: 19, name: track, image: track.png }
  - { min_zoom: 8, max_zoom: 19, name: cycleway, image: cycleway.png }
  - { min_zoom: 5, max_zoom: 12, name: cycleway_national, image: cycleway_national.png }
  - { min_zoom: 13, max_zoom: 19, name: cycleway_national, image: cycleway_national13.png }
  - { min_zoom: 5, max_zoom: 12, name: cycleway_regional, image: cycleway_regional.png }
  - { min_zoom: 13, max_zoom: 19, name: cycleway_regional, image: cycleway_regional13.png }
  - { min_zoom: 8, max_zoom: 12, name: cycleway_local, image: cycleway_local.png }
  - { min_zoom: 13, max_zoom: 19, name: cycleway_local, image: cycleway_local13.png }
  - { min_zoom: 13, max_zoom: 19, name: footway, image: footway.png }
  - { min_zoom: 7, max_zoom: 13, name: rail, image: rail.png }
  - { min_zoom: 14, max_zoom: 19, name: rail, image: rail14.png }
  - { min_zoom: 9, max_zoom: 19, name: forest, image: forest.png }
  - { min_zoom: 10, max_zoom: 19, name: common, image: common.png }
  - { min_zoom: 7, max_zoom: 19, name: lake, image: lake.png }
  - { min_zoom: 14, max_zoom: 19, name: bicycle_shop, image: bicycle_shop.png }
  - { min_zoom: 14, max_zoom: 19, name: bicycle_parking, image: bicycle_parking.png }
  - { min_zoom: 16, max_zoom: 19, name: toilets, image: toilets.png }
opnvkarte:
  - { min_zoom:  6, name: rail, width: 52, height: 1, fill: "#868686" }
  - { min_zoom:  8, name: rail, width: 52, height: 2, fill: "#868686" }
  - { min_zoom: 11, name: rail, image: rail11.svg }
  - { min_zoom: 15, name: rail, image: rail15.svg }
  - { min_zoom: 17, name: rail, image: rail17.svg }
  - { min_zoom:  6, name: train, width: 52, height:  2, fill: "#ffc366" }
  - { min_zoom: 10, name: train, width: 52, height:  3, fill: "#ffc366" }
  - { min_zoom: 12, name: train, width: 52, height:  4, fill: "#ffc366" }
  - { min_zoom: 14, name: train, width: 52, height:  8, fill: "#ffc366" }
  - { min_zoom: 16, name: train, width: 52, height: 10, fill: "#ffc366" }
  - { min_zoom: 10, name: light_rail, width: 52, height:  3, fill: "#66ff66" }
  - { min_zoom: 12, name: light_rail, width: 52, height:  4, fill: "#66ff66" }
  - { min_zoom: 14, name: light_rail, width: 52, height:  8, fill: "#66ff66" }
  - { min_zoom: 16, name: light_rail, width: 52, height: 10, fill: "#66ff66" }
  - { min_zoom: 10, name: tram_only, width: 52, height:  3, fill: "#3333fe" }
  - { min_zoom: 12, name: tram_only, width: 52, height:  4, fill: "#3333fe" }
  - { min_zoom: 14, name: tram_only, width: 52, height:  8, fill: "#3333fe" }
  - { min_zoom: 16, name: tram_only, width: 52, height: 10, fill: "#3333fe" }
  - { min_zoom: 10, name: subway, width: 52, height:  3, fill: "#33339f" }
  - { min_zoom: 12, name: subway, width: 52, height:  4, fill: "#33339f" }
  - { min_zoom: 14, name: subway, width: 52, height:  8, fill: "#33339f" }
  - { min_zoom: 16, name: subway, width: 52, height: 10, fill: "#33339f" }
  - { min_zoom:  9, name: ferry, width: 52, height: 2, fill: "#9f339f" }
  - { min_zoom: 14, name: ferry, width: 52, height: 3, fill: "#9f339f" }
  - { min_zoom: 10, name: trolleybus, width: 52, height:  3, fill: "#9f3333" }
  - { min_zoom: 12, name: trolleybus, width: 52, height:  4, fill: "#9f3333" }
  - { min_zoom: 14, name: trolleybus, width: 52, height:  8, fill: "#9f3333" }
  - { min_zoom: 16, name: trolleybus, width: 52, height: 10, fill: "#9f3333" }
  - { min_zoom: 11, name: bus, width: 52, height:  1, fill: "#fe3333" }
  - { min_zoom: 12, name: bus, width: 52, height:  2, fill: "#fe3333" }
  - { min_zoom: 13, name: bus, width: 52, height:  3, fill: "#fe3333" }
  - { min_zoom: 14, name: bus, width: 52, height:  4, fill: "#fe3333" }
  - { min_zoom: 16, name: bus, width: 52, height: 10, fill: "#fe3333" }
  - { min_zoom: 13, name: bus_stop, image: bus_stop13.svg }
  - { min_zoom: 15, name: bus_stop, image: bus_stop15.svg }
  - { min_zoom: 13, name: stop, image: stop13.svg }
  - { min_zoom: 15, name: stop, image: stop15.svg }
