mapnik:
  - { min_zoom: 0, max_zoom: 19, name: motorway, image: motorway.png }
  - { min_zoom: 0, max_zoom: 11, name: trunk, image: trunk.png }
  - { min_zoom: 12, max_zoom: 19, name: trunk, image: trunk12.png }
  - { min_zoom: 7, max_zoom: 11, name: primary, image: primary.png }
  - { min_zoom: 12, max_zoom: 19, name: primary, image: primary12.png }
  - { min_zoom: 9, max_zoom: 11, name: secondary, image: secondary.png }
  - { min_zoom: 12, max_zoom: 19, name: secondary, image: secondary12.png }
  - { min_zoom: 13, max_zoom: 19, name: unsurfaced, image: unsurfaced.png }
  - { min_zoom: 13, max_zoom: 19, name: track, image: track.png }
  - { min_zoom: 13, max_zoom: 19, name: byway, image: byway.png }
  - { min_zoom: 13, max_zoom: 19, name: bridleway, image: bridleway.png }
  - { min_zoom: 13, max_zoom: 19, name: cycleway, image: cycleway.png }
  - { min_zoom: 13, max_zoom: 19, name: footway, image: footway.png }
  - { min_zoom: 8, max_zoom: 12, name: rail, image: rail.png }
  - { min_zoom: 13, max_zoom: 19, name: rail, image: rail13.png }
  - { min_zoom: 13, max_zoom: 19, name: subway, image: subway.png }
  - { min_zoom: 13, max_zoom: 19, name: tram, image: tram.png }
  - { min_zoom: 12, max_zoom: 19, name: cable, image: cable.png }
  - { min_zoom: 11, max_zoom: 19, name: runway, image: runway.png }
  - { min_zoom: 12, max_zoom: 19, name: apron, image: apron.png }
  - { min_zoom: 0, max_zoom: 19, name: admin, image: admin.png }
  - { min_zoom: 9, max_zoom: 19, name: forest, image: forest.png }
  - { min_zoom: 10, max_zoom: 19, name: wood, image: wood.png }
  - { min_zoom: 10, max_zoom: 19, name: golf, image: golf.png }
  - { min_zoom: 10, max_zoom: 19, name: park, image: park.png }
  - { min_zoom: 8, max_zoom: 19, name: resident, image: resident.png }
  - { min_zoom: 10, max_zoom: 19, name: tourist, image: tourist.png }
  - { min_zoom: 10, max_zoom: 19, name: common, image: common.png }
  - { min_zoom: 10, max_zoom: 19, name: retail, image: retail.png }
  - { min_zoom: 10, max_zoom: 19, name: industrial, image: industrial.png }
  - { min_zoom: 10, max_zoom: 19, name: commercial, image: commercial.png }
  - { min_zoom: 10, max_zoom: 19, name: heathland, image: heathland.png }
  - { min_zoom: 7, max_zoom: 19, name: lake, image: lake.png }
  - { min_zoom: 10, max_zoom: 19, name: farm, image: farm.png }
  - { min_zoom: 10, max_zoom: 19, name: brownfield, image: brownfield.png }
  - { min_zoom: 11, max_zoom: 19, name: cemetery, image: cemetery.png }
  - { min_zoom: 11, max_zoom: 19, name: allotments, image: allotments.png }
  - { min_zoom: 11, max_zoom: 19, name: pitch, image: pitch.png }
  - { min_zoom: 11, max_zoom: 19, name: centre, image: centre.png }
  - { min_zoom: 11, max_zoom: 19, name: reserve, image: reserve.png }
  - { min_zoom: 11, max_zoom: 19, name: military, image: military.png }
  - { min_zoom: 12, max_zoom: 19, name: school, image: school.png }
  - { min_zoom: 12, max_zoom: 19, name: building, image: building.png }
  - { min_zoom: 12, max_zoom: 19, name: station, image: station.png }
  - { min_zoom: 12, max_zoom: 19, name: summit, image: summit.png }
  - { min_zoom: 12, max_zoom: 19, name: tunnel, image: tunnel.png }
  - { min_zoom: 13, max_zoom: 19, name: bridge, image: bridge.png }
  - { min_zoom: 15, max_zoom: 19, name: private, image: private.png }
  - { min_zoom: 15, max_zoom: 19, name: permissive, image: permissive.png }
  - { min_zoom: 15, max_zoom: 19, name: destination, image: destination.png }
  - { min_zoom: 12, max_zoom: 19, name: construction, image: construction.png }
cyclemap:
  - { min_zoom: 0, max_zoom: 11, name: motorway, image: motorway.png }
  - { min_zoom: 12, max_zoom: 19, name: motorway, image: motorway12.png }
  - { min_zoom: 0, max_zoom: 11, name: trunk, image: trunk.png }
  - { min_zoom: 12, max_zoom: 19, name: trunk, image: trunk12.png }
  - { min_zoom: 7, max_zoom: 11, name: primary, image: primary.png }
  - { min_zoom: 12, max_zoom: 19, name: primary, image: primary12.png }
  - { min_zoom: 9, max_zoom: 11, name: secondary, image: secondary.png }
  - { min_zoom: 12, max_zoom: 19, name: secondary, image: secondary12.png }