- leafletOsmId: "Mapnik"
  code: "M"
  layerId: "mapnik"
  nameId: "standard"
  wiki: "https://wiki.openstreetmap.org/wiki/OpenStreetMap_Carto"
  canEmbed: true
  canDownloadImage: true
  maxZoom: 19
  tileUrl: "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true

- leafletOsmId: "CyclOSM"
  code: "Y"
  layerId: "cyclosm"
  nameId: "cyclosm"
  wiki: "https://wiki.openstreetmap.org/wiki/CyclOSM"
  canEmbed: true
  maxZoom: 20
  tileUrl: "https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png"
  subdomains: [a, b, c]
  credit:
    id: "cyclosm_credit"
    children:
      cyclosm_link:
        id: "cyclosm_name"
        href: "https://www.cyclosm.org"
      osm_france_link:
        id: "osm_france"
        href: "https://openstreetmap.fr/"

- leafletOsmId: "CycleMap"
  code: "C"
  layerId: "cyclemap"
  nameId: "cycle_map"
  wiki: "https://wiki.openstreetmap.org/wiki/OpenCycleMap"
  apiKeyId: "thunderforest_key"
  canEmbed: true
  canDownloadImage: true
  maxZoom: 21
  tileUrl: "https://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}{ratio}.png?apikey={apikey}"
  subdomains: [a, b, c]
  credit:
    id: "thunderforest_credit"
    children:
      thunderforest_link:
        id: "andy_allan"
        href: "https://www.thunderforest.com/"

- leafletOsmId: "TransportMap"
  leafletOsmDarkId: "TransportDarkMap"
  code: "T"
  layerId: "transportmap"
  nameId: "transport_map"
  wiki: "https://wiki.openstreetmap.org/wiki/Transport_Map"
  apiKeyId: "thunderforest_key"
  canEmbed: true
  canDownloadImage: true
  maxZoom: 21
  tileUrl: "https://{s}.tile.thunderforest.com/transport/{z}/{x}/{y}{ratio}.png?apikey={apikey}"
  tileUrlDark: "https://{s}.tile.thunderforest.com/transport-dark/{z}/{x}/{y}{ratio}.png?apikey={apikey}"
  subdomains: [a, b, c]
  credit:
    id: "thunderforest_credit"
    children:
      thunderforest_link:
        id: "andy_allan"
        href: "https://www.thunderforest.com/"

- leafletOsmId: "TracestrackTopo"
  code: "P"
  layerId: "tracestracktopo"
  nameId: "tracestracktop_topo"
  wiki: "https://wiki.openstreetmap.org/wiki/Tracestrack"
  apiKeyId: "tracestrack_key"
  maxZoom: 19
  tileUrl: "https://tile.tracestrack.com/topo__/{z}/{x}/{y}.webp?key={apikey}"
  credit:
    id: "tracestrack_credit"
    children:
      tracestrack_link:
        id: "tracestrack"
        href: "https://www.tracestrack.com/"

- leafletOsmId: "HOT"
  code: "H"
  layerId: "hot"
  nameId: "hot"
  wiki: "https://wiki.openstreetmap.org/wiki/Humanitarian"
  canEmbed: true
  maxZoom: 20
  tileUrl: "https://tile-{s}.openstreetmap.fr/hot/{z}/{x}/{y}.png"
  subdomains: [a, b, c]
  credit:
    id: "hotosm_credit"
    children:
      hotosm_link:
        id: "hotosm_name"
        href: "https://www.hotosm.org/"
      osm_france_link:
        id: "osm_france"
        href: "https://openstreetmap.fr/"

- leafletOsmId: "ShortbreadColorful"
  leafletOsmDarkId: "ShortbreadEclipse"
  code: "S"
  layerId: "shortbread"
  nameId: "shortbread"
  wiki: "https://wiki.openstreetmap.org/wiki/Shortbread"
  canEmbed: true
  maxZoom: 23
  isVectorStyle: true
  styleUrl: "https://vector.openstreetmap.org/styles/shortbread/colorful.json"
  styleUrlDark: "https://vector.openstreetmap.org/styles/shortbread/eclipse.json"
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true

- leafletOsmId: "OpenMapTiles"
  code: "V"
  layerId: "openmaptiles_osm"
  nameId: "openmaptiles_osm"
  wiki: "https://wiki.openstreetmap.org/wiki/MapTiler"
  apiKeyId: "maptiler_key"
  maxZoom: 23
  isVectorStyle: true
  styleUrl: "https://api.maptiler.com/maps/openstreetmap/style.json?key={apikey}"
  credit:
    id: "openmaptiles_credit"
    children:
      openmaptiles_link:
        id: "openmaptiles_name"
        href: "https://openmaptiles.org/"
      maptiler_link:
        id: "maptiler_name"
        href: "https://www.maptiler.com/"
