- leafletOsmId: "Mapnik"
  code: "M"
  layerId: "mapnik"
  nameId: "standard"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "make_a_donation"
    href: "https://supporting.openstreetmap.org"
    donate: true

- leafletOsmId: "CyclOSM"
  code: "Y"
  layerId: "cyclosm"
  nameId: "cyclosm"
  canEmbed: true
  credit:
    id: "cyclosm_credit"
    children:
      cyclosm_link:
        id: "cyclosm_name"
        href: "https://www.cyclosm.org"
      osm_france_link:
        id: "osm_france"
        href: "https://openstreetmap.fr/"

- leafletOsmId: "CycleMap"
  code: "C"
  layerId: "cyclemap"
  nameId: "cycle_map"
  apiKeyId: "thunderforest_key"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "thunderforest_credit"
    children:
      thunderforest_link:
        id: "andy_allan"
        href: "https://www.thunderforest.com/"

- leafletOsmId: "TransportMap"
  leafletOsmDarkId: "TransportDarkMap"
  code: "T"
  layerId: "transportmap"
  nameId: "transport_map"
  apiKeyId: "thunderforest_key"
  canEmbed: true
  canDownloadImage: true
  credit:
    id: "thunderforest_credit"
    children:
      thunderforest_link:
        id: "andy_allan"
        href: "https://www.thunderforest.com/"

- leafletOsmId: "TracestrackTopo"
  code: "P"
  layerId: "tracestracktopo"
  nameId: "tracestracktop_topo"
  apiKeyId: "tracestrack_key"
  credit:
    id: "tracestrack_credit"
    children:
      tracestrack_link:
        id: "tracestrack"
        href: "https://www.tracestrack.com/"

- leafletOsmId: "HOT"
  code: "H"
  layerId: "hot"
  nameId: "hot"
  canEmbed: true
  credit:
    id: "hotosm_credit"
    children:
      hotosm_link:
        id: "hotosm_name"
        href: "https://www.hotosm.org/"
      osm_france_link:
        id: "osm_france"
        href: "https://openstreetmap.fr/"
