"action_createpoi": đang tạo địa điểm
"hint_pointselected": đã chọn điểm\n(shift-nhấn chuột để\nbắt đầu lối mới)
"action_movepoint": đang chuyển điểm
"hint_drawmode": nhấn chuột để thêm điểm\nnhấn đúp/Enter\nđể kết thúc lối
"hint_overendpoint": đang trên điểm kết thúc\nnhấn chuột để nối\nshift-nhấn chuột để hợp nhất
"hint_overpoint": đang trên điểm\nnhấn chuột để nối"
"gpxpleasewait": Xin chờ, đang xử lý tuyến đường GPX.
"revert": Lùi
"cancel": Hủy bỏ
"prompt_revertversion": "Lùi lại phiên bản cũ hơn:"
"tip_revertversion": Chọn phiên bản để lùi lại
"action_movepoi": đang chuyển địa điểm
"tip_splitway": Chia cắt lối tại điểm đã chọn (X)
"tip_direction": Hướng của lối - nhấn để đảo ngược
"tip_clockwise": Lối vòng theo chiều kim đồng hồ - nhấn để đảo ngược
"tip_anticlockwise": Lối vòng ngược chiều kim đồng hồ - nhấn để đảo ngược
"tip_noundo": Không có gì để lùi
"action_mergeways": đang hợp nhất hai lối
"tip_gps": Hiện các tuyến đường GPS (G)
"tip_options": Tùy chỉnh (chọn nền bản đồ)
"tip_addtag": Thêm thẻ mới
"tip_addrelation": Xếp vào quan hệ
"tip_repeattag": Chép các thẻ từ lối được chọn trước (R)
"tip_alert": Đã gặp lỗi - nhấn để xem chi tiết
"hint_toolong": "dài quá không thể mở khóa:\nxin chia cắt nó thành\ncác lối ngắn hơn"
"hint_loading": đang tải các lối
"prompt_welcome": Hoan nghênh bạn đã đến OpenStreetMap!
"prompt_introduction": Hãy chọn cách sử dụng ở dưới để bắt đầu sửa đổi. Nút "Bắt đầu" để cho bạn sửa đổi thẳng bản đồ chính - các thay đổi thường hiện ra mỗi thứ năm. Nút 'Nghịch ngợm' để cho bạn thử sửa đổi, các thay đổi của bạn không được lưu.\n\nHãy nhớ các quy tắc vàng của OpenStreetMap:\n\n
"prompt_dontcopy": Đừng sao chép từ bản đồ khác
"prompt_accuracy": Cần chính xác - chỉ vẽ những nơi đã thăm
"prompt_enjoy": Và chúc vui vẻ!
"dontshowagain": Không hiện thông báo này lần sau
"prompt_start": Bắt đầu đóng góp vào bản đồ OpenStreetMap.
"prompt_practise": Thử vẽ bản đồ - các thay đổi của bạn không được lưu.
"practicemode": Chế độ thử
"help": Trợ giúp
"prompt_help": Tìm hiểu cách sử dụng Potlatch, trình vẽ bản đồ này.
"track": Tuyến đường
"prompt_track": Chuyển đổi tuyến đường GPS thành các lối (khóa) để sửa đổi.
"action_deletepoint": đang xóa điểm
"deleting": đang xóa
"action_cancelchanges": đang hủy bỏ các thay đổi
"emailauthor": \n\nXin gửi thư điện tử cho richard\@systemeD.net báo cáo lỗi và giải thích bạn làm gì lúc khi gặp lỗi.
"error_connectionfailed": "Rất tiếc - không thể kết nối với máy chủ OpenStreetMap. Những thay đổi gần đây có thể chưa được lưu.\n\nBạn có muốn thử lại không?"
"option_background": "Nền:"
"option_fadebackground": Nhạt màu nền
"option_thinlines": Hiện đường hẹp ở các tỷ lệ
"option_custompointers": Hiện con trỏ bút và tay
"tip_presettype": Chọn các loại thẻ được định trước trong trình đơn.
"action_waytags": đang gắn thẻ vào lối
"action_pointtags": đang gắn thẻ vào điểm
"action_poitags": đang gắn thẻ vào địa điểm
"action_addpoint": đang thêm nốt vào cuối lối
"add": Thêm
"prompt_addtorelation": Xếp $1 vào quan hệ
"prompt_selectrelation": Chọn một quan hệ đã tồn tại để xếp vào, hoặc tạo ra quan hệ mới.
"createrelation": Tạo quan hệ mới
"tip_selectrelation": Thêm vào tuyến đường đã chọn
"action_reverseway": đang đảo ngược lối
"tip_undo": Lùi $1 (Z)
"error_noway": Không tìm thấy $1 (có lẽ bạn đã kéo ra khỏi vùng?) nên không thể lùi lại.
"error_nosharedpoint": Các lối $1 và $2 không còn cắt ngang nhau tại điểm nào, nên không thể lùi lại việc chia cắt lối.
"error_nopoi": Không tìm thấy địa điểm (có lẽ bạn đã kéo ra khỏi vùng?) nên không thể lùi lại.
"prompt_taggedpoints": Một số điểm trên lối này đã được gắn thẻ. Bạn có chắc muốn xóa nó?
"action_insertnode": đang gắn nốt vào lối
"action_splitway": đang chia cắt lối
"editingmap": Sửa đổi bản đồ
"start": Bắt đầu
"play": Nghịch ngợm
"delete": Xóa
"a_way": $1 lối
"a_poi": $1 địa điểm
"action_moveway": đang chuyển lối
"way": Lối
"point": Điểm
"ok": OK
"existingrelation": Xếp vào quan hệ đã tồn tại
"findrelation": Tìm kiếm quan hệ chứa
"norelations": Không có quan hệ trong vùng này
"advice_toolong": Dài quá không thể mở khóa - xin chia cắt nó thành các lối ngắn hơn
"advice_waydragged": Đã kéo lối (Z để lùi lại)
"advice_tagconflict": Các thẻ không hợp - xin kiểm tra lại
"advice_nocommonpoint": Các lối không cắt ngang nhau tại điểm nào
"option_warnings": Nổi các cảnh báo
"reverting": đang lùi sửa
