"action_createpoi": Crear un punto de interés (POI)
"hint_pointselected": Punto seleccionado\n(shift-clic en el punto para\nempezar nueva línea)
"action_movepoint": Mover un punto
"hint_drawmode": Clic para añadir un punto\ndoble-clic/Return\npara terminar la línea
"hint_overendpoint": Sobre punto final\nclic para unir\nshift-clic para combinar
"hint_overpoint": Sobre punto\nclick para unir"
"gpxpleasewait": Por favor espere un poco mientras el track GPX se procesa.
"revert": Volver
"cancel": Cancelar
"prompt_revertversion": "Volver a una versión previamente guardada:"
"tip_revertversion": Elige la versión a la que volver.
"action_movepoi": Mover un punto de interés (POI)
"tip_splitway": Dividir la vía en el punto seleccionado (X)
"tip_direction": Dirección de la vía - clic para invertir la dirección de la vía
"tip_clockwise": Vía circular en el sentido de las agujas del reloj - clic para invertir la dirección de la vía
"tip_anticlockwise": Vía circular en el sentido contrario de las agujas del reloj - clic para invertir la dirección de la vía
"tip_noundo": Nada que deshacer
"action_mergeways": Combinar dos vías
"tip_gps": Mostrar los tracks de GPS (G)
"tip_options": Opciones (elegir el fondo del mapa)
"tip_addtag": Añadir un nuevo parámetro (tag)
"tip_addrelation": Añadir a una relación
"tip_repeattag": Repetir los parámetros (tags) de la vía seleccionada previamente (R)
"tip_alert": Ha ocurrido un error - clic para detalles
"hint_toolong": "Demasiado larga para desbloquear:\nPorfavor divida\nen vías más cortas"
"hint_loading": Cargando vías
"prompt_welcome": Bienvenido a OpenStreetMap!
"prompt_introduction": Seleccione uno de los botones más abajo para empezar a editar. Si pulsa "Empezar", estará editando directamente el mapa - Normalmente los cambios se mostrarán cada Jueves. Si pulsa "Practicar", sus cambios no se guardarán, de esta manera podrá practicar la edición.\n\nRecuerde las reglas de oro de OpenStreetMap:\n\n
"prompt_dontcopy": No copie de otros mapas
"prompt_accuracy": La precisión es importante - Mapee solo zonas en las que ha estado físicamente.
"prompt_enjoy": Y páselo bien!
"dontshowagain": No mostrar este mensaje de nuevo
"prompt_start": Empezar a mapear con OpenStreetMap.
"prompt_practise": Mapear en prácticas - Sus cambios no se guardarán.
"practicemode": Modo prácticas
"help": Ayuda
"prompt_help": Encuentre cómo usar Potlatch (éste editor de mapas).
"track": Track
"prompt_track": Convierta su track de GPS a vías (bloqueadas) para editar.
"action_deletepoint": Borrar un punto
"deleting": Borrar
"action_cancelchanges": Cancelar cambios
"emailauthor": \n\nPor favor envíe un mail a richard\@systemeD.net con un informe del error, describiendo lo que hacía en ese momento.
"error_connectionfailed": "Disculpe - la conexión al servidor de OpenStreetMap ha fallado. Cualquier cambio reciente no se ha guardado.\n\nPodría intentarlo de nuevo?"
"option_background": "Fondo:"
"option_fadebackground": Atenuar fondo
"option_thinlines": Usar líneas finas en todas las escalas
"option_custompointers": Usar punteros de pluma y mano
"tip_presettype": Seleccionar que tipo de parámetros (tags) preestablecidos se ofrecen en el menú.
"action_waytags": Parámetros (tags) en una vía
"action_pointtags": Parámetros (tags) un punto
"action_poitags": Parámetros (tags) en un punto de interés (POI)
"action_addpoint": Añadir un punto al final de una vía
"add": Añadir
"prompt_addtorelation": Añadir $1 a una relación
"prompt_selectrelation": Seleccionar una relación existente para añadir a ella, o crear una nueva relación.
"createrelation": Crear una nueva relación
"tip_selectrelation": Añadir a la ruta seleccionada
"action_reverseway": Invertir dirección de una vía
"tip_undo": Deshacer $1 (Z)
"error_noway": La vía $1 no se puede encontrar (igual usted se ha desplazado a otra zona?), por tanto no se puede deshacer..
"error_nosharedpoint": Las vías $1 y $2 ya no tienen ningún punto en común, por tanto no se pueden dividir.
"error_nopoi": El punto de interés (POI) no se puede encontrar (igual usted se ha desplazado a otra zona?), por tanto no se puede deshacer.
"prompt_taggedpoints": Algunos puntos de esta vía tienen parámetros (tags). Seguro que quiere borrar?
"action_insertnode": Añadir un punto a una vía
"action_splitway": Dividir una vía
"editingmap": Editando el mapa
"start": Empezar
"play": Practicar
"delete": Borrar
"a_way": $1 una vía
"a_poi": $1 un punto de interés (POI)
"action_moveway": Moviendo una vía
"way": Vía
"point": Punto
"ok": OK
"existingrelation": Añadir a relación existente
"findrelation": Buscar una relación que contenga
"norelations": No hay relaciones en el área actual
"advice_toolong": Demasiado largo para desbloquear - Por favor divídalo en vías más cortas
"advice_waydragged": Vía desplazada (Z para deshacer)
"advice_tagconflict": Los parámetros no coinciden - Por favor revíselos (Z para deshacer)
"advice_nocommonpoint": Las vías no comparten un punto en común
"option_warnings": Mostrar alertas flotantes
"reverting": revirtiendo
"prompt_helpavailable": Tiene cambios sin guardar. (Para guardar en Potlach, debería deseleccionar la vía o el punto actual.)
