"action_createpoi": creazione PDI...
"hint_pointselected": punto selezionato\n(shift-clic sul punto per\niniziare una nuova linea)
"action_movepoint": spostamento punto...
"hint_drawmode": clic per aggiungere un punto\ndoppio clic/Return\nper terminare la linea
"hint_overendpoint": su punto terminale\nclic per congiungere\nshift-clic per unire
"hint_overpoint": su punto\nclic per congiungere"
"gpxpleasewait": Attendere mentre la traccia GPX viene elaborata.
"revert": Ripristina
"cancel": Annulla
"prompt_revertversion": "Ripristina una versione precedente:"
"tip_revertversion": Scegliere la versione da ripristinare
"action_movepoi": spostamento PDI...
"tip_splitway": Separa percorso nel punto selezionato (X)
"tip_direction": Direzione del percorso - clic per invertire
"tip_clockwise": Percorso circolare orario - clic per invertire
"tip_anticlockwise": Percorso circolare antiorario - clic per invertire
"tip_noundo": Nulla da annullare
"action_mergeways": unione di due percorsi...
"tip_gps": Mostra le tracce GPS (G)
"tip_options": Imposta le opzioni (scegli lo sfondo della mappa)
"tip_addtag": Aggiungi una nuova etichetta
"tip_addrelation": Aggiungi ad una relazione
"tip_repeattag": Ripeti le etichette del percorso precedentemente selezionato (R)
"tip_alert": Si è verificato un errore (clic per i dettagli)
"hint_toolong": "troppo lungo per sbloccare:\ndividere in\npercorsi più brevi"
"hint_loading": caricamento percorsi...
"prompt_welcome": Benvenuti su OpenStreetMap!
"prompt_introduction": "Scegli un pulsante per iniziare la modifica. Se fai clic su 'Inizia' modificherai direttamente la mappa principale (le modifiche di solito sono visibili ogni giovedì). Se fai clic su 'Gioca' le modifiche non saranno salvate, quindi potrai esercitarti.\n\nRicorda le regole d'oro di OpenStreetMap:\n\n"
"prompt_dontcopy": Non copiare da altre mappe
"prompt_accuracy": "L'accuratezza è importante - mappa solo posti dove sei stato"
"prompt_enjoy": E soprattutto, buon divertimento!
"dontshowagain": Non mostrare più questo messaggio
"prompt_start": Inizia a mappare con OpenStreetMap.
"prompt_practise": "Inizia l'esercitazione (le modifiche non saranno salvate)."
"practicemode": Esercitazione
"help": Aiuto
"prompt_help": Impara ad usare Potlatch, questo editor di mappe.
"track": Traccia
"prompt_track": Converti la tua traccia GPS in percorsi (bloccati) per la modifica.
"action_deletepoint": cancellazione punto...
"deleting": cancellazione...
"action_cancelchanges": annullamento modifiche a
"emailauthor": "\n\nInviare un'e-mail a richard\@systemeD.net con la segnalazione dell'errore, descrivendo cosa si stava facendo nel momento in cui si è verificato."
"error_connectionfailed": "La connessione con il server di OpenStreetMap si è interrotta. Qualsiasi modifica recente non è stata salvata.\n\nRiprovare?"
"option_background": "Sfondo:"
"option_fadebackground": Sfondo sfumato
"option_thinlines": Usa linee sottili a tutte le scale
"option_custompointers": Usa puntatori penna e mano
"tip_presettype": Scegli che tipo di preset mostrare nel menu.
"action_waytags": impostazione etichette su un percorso...
"action_pointtags": impostazione etichette su un punto...
"action_poitags": impostazione etichette su un PDI...
"action_addpoint": aggiunta nodo alla fine di un percorso...
"add": Aggiungi
"prompt_addtorelation": Aggiungi $1 ad una relazione
"prompt_selectrelation": Selezionare una relazione esistente a cui aggiungere o creare una nuova relazione.
"createrelation": Crea una nuova relazione
"tip_selectrelation": Aggiungi alla rotta scelta
"action_reverseway": inversione percorso...
"tip_undo": Annulla $1 (Z)
"error_noway": "Impossibile trovare il percorso $1 (forse è fuori dallo schermo?): impossibile annullare."
"error_nosharedpoint": "I percorsi $1 e $2 non hanno più un punto comune: impossibile annullare la separazione."
"error_nopoi": "Impossibile trovare il PDI (forse è fuori dallo schermo?): impossibile annullare."
"prompt_taggedpoints": Alcuni dei punti di questo percorso sono etichettati. Cancellare davvero?
"action_insertnode": aggiunta di un nodo in un percorso...
"action_splitway": separazione di un percorso...
"editingmap": Modifica
"start": Inizia
"play": Gioca
"delete": Cancella
"a_way": $1 un percorso
"a_poi": $1 un PDI
"action_moveway": spostamento percorso
"way": Percorso
"point": Punto
"ok": OK
"existingrelation": Aggiungi ad una relazione esistente
"findrelation": Trova una relazione che contiene
"norelations": "Nessuna relazione nell'area attuale"
"advice_toolong": "Troppo lungo per sbloccare: separa in percorsi più brevi"
"advice_waydragged": Percorso trascinato (Z per annullare)
"advice_tagconflict": "Le etichette non corrispondono: controllare (Z per annullare)"
"advice_nocommonpoint": I percorsi non hanno nessun punto comune
"option_warnings": Mostra avvertimenti galleggianti
"reverting": annullo...
