"action_createpoi": Maak een POI (nuttige plaats)
"hint_pointselected": Punt geselecteerd\n(shift-klik op het punt om een nieuwe lijn te\nbeginnen)
"action_movepoint": Verplaats een punt
"hint_drawmode": Klik om een nieuw punt toe te voegen\ndubbelklik/enter\n om de lijn te stoppen
"hint_overendpoint": "Eindpunt van een way:\nKlik om dit punt toe te voegen\nShift-klik om beide ways samen te voegen"
"hint_overpoint": "Punt:\nKlik om dit punt toe te voegen"
"gpxpleasewait": Even geduld alstublieft, terwijl de GPX trace wordt verwerkt
"revert": Teruggaan naar een oudere versie
"cancel": Annuleren
"prompt_revertversion": "Teruggaan naar een oudere versie:"
"tip_revertversion": Kies naar welke versie moet worden teruggegaan
"action_movepoi": Verplaats de POI (nuttige plaats)
"tip_splitway": "Splits de 'way' op het geselecteerde punt (X)"
"tip_direction": "Richting van de 'way' - Klik om de richting om te draaien"
"tip_clockwise": "Gesloten 'way' die met de klok meegaat - Klik om om te draaien"
"tip_anticlockwise": "Gesloten 'way' die tegen de klok ingaat - Klik om om te draaien"
"tip_noundo": Niets ongedaan te maken
"action_mergeways": twee wegen samenvoegen
"tip_gps": Laat de gps-tracks zien (G)
"tip_options": Opties (kies de achtergrondkaart)
"tip_addtag": Voeg een nieuwe tag toe
"tip_addrelation": Voeg toe aan een relatie
"tip_repeattag": "Herhaal de tags van de vorige geselecteerde 'way' (R)"
"tip_alert": Foutmelding - Klik voor meer details
"hint_toolong": "Te lang om vrij te geven:\nSplits\n de 'ways' in kleinere stukken"
"hint_loading": "Bezig de 'ways' te laden"
"prompt_welcome": Welkom bij OpenStreetMap!
"prompt_introduction": "Klik beneden op een knop om te beginnen met mappen. Als u klikt op 'Start', wijzigt u de kaart direct. De veranderingen zijn gewoonlijk elke donderdag te zien op de kaart. Als u klikt op 'Oefenen', zullen uw wijzingen niet bewaard worden, zodat u kunt oefenen.\n\nOnthoud de belangrijkste regels van OpenStreetMap:\n\n"
"prompt_dontcopy": Kopieer nooit van andere kaarten
"prompt_accuracy": Precisie is belangrijk - breng alleen gebieden die u kent in kaart
"prompt_enjoy": En veel plezier!
"dontshowagain": Laat dit bericht niet meer zien
"prompt_start": Begin te mappen met OpenStreetMap
"prompt_practise": Oefenen - Veranderingen worden niet bewaard
"practicemode": Oefenmodus
"help": Help
"prompt_help": Leer hoe u Potlatch, deze applicatie, moet gebruiken
"track": Track
"prompt_track": "Converteer uw gps-tracks in 'ways' om deze te gebruiken"
"action_deletepoint": Verwijder een punt
"deleting": verwijder
"action_cancelchanges": veranderingen ongedaan maken naar
"emailauthor": \n\nStuur een mail naar richard\@systemeD.net met een bug report, schrijf wat je aan het doen was.
"error_connectionfailed": "Sorry - de verbinding met de server is verbroken. Recente veranderingen zijn misschien niet opgeslagen.\n\nOpnieuw proberen?"
"option_background": "Achtergrond:"
"option_fadebackground": Achtergrond lichter maken
"option_thinlines": Altijd dunne lijnen gebruiken
"option_custompointers": Pen- en handcursors gebruiken
"tip_presettype": Kies welk type presets in het menu getoond moet worden.
"action_waytags": "tags instellen op een 'way'"
"action_pointtags": "tags instellen op een 'point'"
"action_poitags": tags instellen op een POI
"action_addpoint": "'Node' toevoegen aan eind van de 'way'"
"add": Toevoegen
"prompt_addtorelation": Voeg $1 toe aan een relatie
"prompt_selectrelation": Selecteer een relatie om aan toe te voegen, of maak een nieuwe.
"createrelation": Nieuwe relatie maken
"tip_selectrelation": Toevoegen aan gekozen route
"action_reverseway": "'Way' omdraaien"
"tip_undo": $1 ongedaan maken (Z)
"error_noway": "'Way' $1 niet gevonden (hebt u de kaart weggeschoven?), kan dus niet ongedaan maken."
"error_nosharedpoint": "De 'ways' $1 en $2 hebben geen gemeenschappelijk punt meer, dus ik kan het splitsen niet ongedaan maken."
"error_nopoi": POI niet gevonden (hebt u de kaart weggeschoven?), kan dus niet ongedaan maken.
"prompt_taggedpoints": "Enkele punten op deze 'way' hebben tags. Wil je hem zeker verwijderen?"
"action_insertnode": "Punt toevoegen aan 'way'"
"action_splitway": "'Way' splitsen"
"editingmap": Kaart aanpassen
"start": Start
"play": Oefenen
"delete": Verwijderen
"a_way": "$1 een 'way'"
"a_poi": $1 een POI
"action_moveway": "'Way' verplaatsen"
"way": "'Way'"
"point": Punt
"ok": OK
"existingrelation": Toevoegen aan bestaande relatie
"findrelation": Relatie zoeken met
"norelations": Geen relaties in huidig gebied
"advice_toolong": "Te lang om te unlocken - splits de 'way' in kortere stukken"
"advice_waydragged": "'Way' verplaatst (Z om ongedaan te maken)"
"advice_tagconflict": Tags komen niet overeen - a.u.b. nakijken (Z om ongedaan te maken)
"advice_nocommonpoint": "De 'ways' hebben geen gemeenschappelijk punt"
"option_warnings": Floating warnings weergeven
"reverting": omdraaien
"prompt_helpavailable": "Er zijn niet-opgeslagen wijzigingen (om op te slaan in Potlatch, moet u de geselecteerde 'way' of POI deselecteren)."
