"action_createpoi": POI készítése
"point": Pont
"hint_pointselected": pont kijelölve\n(shift+kattintás a pontra\núj vonal kezdéséhez)
"action_movepoint": pont mozgatása
"hint_drawmode": kattintás pont hozzáadásához\ndupla kattintás/Enter\na vonal befejezéséhez
"hint_overendpoint": végpont fölött ($1)\nkattintás a csatlakoztatáshoz\nshift+kattintás az egyesítéshez
"hint_overpoint": pont fölött ($1)\nkattintás a csatlakoztatáshoz
"closechangeset": Módosításcsomag bezárása
"prompt_closechangeset": "Módosításcsomag bezárása: $1"
"openchangeset": Módosításcsomag megnyitása
"cancel": Mégse
"ok": OK
"prompt_changesetcomment": "Adj leírást a módosításaidhoz:"
"emailauthor": \n\nKérlek, jelentsd a hibát (angolul) a richard\@systemeD.net e-mail címre, és írd le, hogy mit csináltál akkor, amikor a hiba történt.
"retry": Újra
"error_connectionfailed": Sajnálom - az OpenStreetMap szerverhez való kapcsolódás sikertelen. A legutóbbi módosítások nem lettek elmentve.\n\nSzeretnéd megpróbálni újra?
"error_readfailed": Sajnálom - az OpenStreetMap szerver az adatok lekérdezésekor nem válaszolt.\n\nSzeretnéd megpróbálni újra?
"conflict_waychanged": Amióta elkezdtél szerkeszteni, valaki más módosította a(z) $1$2 vonalat.
"conflict_visitway": "A vonal megtekintéséhez kattints az 'OK'-ra."
"conflict_poichanged": Amióta elkezdtél szerkeszteni, valaki más módosította a(z) $1$2 pontot.
"conflict_visitpoi": "A pont megtekintéséhez kattints az 'OK'-ra."
"conflict_relchanged": Amióta elkezdtél szerkeszteni, valaki más módosította a(z) $1$2 kapcsolatot.
"conflict_download": Az ő változatának letöltése
"conflict_overwrite": Az ő változatának felülírása
"gpxpleasewait": Várj a GPX nyomvonal feldolgozásáig.
"heading_introduction": Bevezetés
"heading_pois": Az első lépések
"heading_surveying": Felmérés
"heading_drawing": Rajzolás
"heading_tagging": Címkézés
"heading_troubleshooting": Hibaelhárítás
"heading_quickref": Gyors referencia
"more": Tovább
"prompt_revertversion": "Korábbi mentett változat visszaállítása:"
"tip_revertversion": Válaszd ki a dátumot a visszaállításhoz
"error_anonymous": Névtelen szerkesztővel nem tudsz kapcsolatba lépni.
"action_revertway": vonal visszaállítása
"drag_pois": Fogd és vidd az érdekes helyeket
"advice_uploadempty": Nincs mit feltölteni
"prompt_savechanges": Módosítások mentése
"uploading": Feltöltés...
"advice_uploadfail": Feltöltés megállítva
"advice_uploadsuccess": Az összes adat sikeresen feltöltve
"action_movepoi": POI mozgatása
"a_poi": POI $1
"tip_splitway": Vonal kettévágása a kijelölt pontnál (X)
"tip_direction": Vonal iránya - kattints a megfordításhoz
"tip_clockwise": Órajárással egyező körkörös vonal - kattints a megfordításhoz
"tip_anticlockwise": Órajárással ellentétes körkörös vonal - kattints a megfordításhoz
"tip_tidy": Vonal pontjainak tisztítása (T)
"tip_noundo": Nincs mit visszavonni
"tip_gps": GPS nyomvonalak megjelenítése (G)
"tip_options": Beállítások módosítása (térkép háttérképének kiválasztása)
"tip_photo": Fényképek betöltése
"tip_addtag": Új címke hozzáadása
"tip_addrelation": Hozzáadás kapcsolathoz
"tip_repeattag": Az előzőleg kiválasztott vonal címkéinek megismétlése (R)
"tip_alert": Hiba történt - kattints a részletekért
"help": Súgó
"manual": Kézikönyv
"way": Vonal
"advice_toolong": Túl hosszú a feloldáshoz - vágd rövidebb szakaszokra
"deleting": törlése
"action_deletepoint": pont törlése
"action_cancelchanges": "módosítások elvetése:"
"custom": "Egyéni:"
"nobackground": Nincs háttérkép
"option_fadebackground": Áttetsző háttér
"option_thinlines": Vékony vonalak használata minden méretaránynál
"option_thinareas": Vékonyabb vonalak használata területekhez
"option_noname": Névtelen utak kiemelése
"option_tiger": Módosítatlan TIGER kiemelése
"option_custompointers": Toll és kéz egérmutatók használata
"option_warnings": Lebegő hibaüzenetek megjelenítése
"option_external": "Külső indítása:"
"option_photo": "Fotó KML:"
"hint_saving_loading": adatok betöltése/mentése
"hint_saving": adatok mentése
"hint_loading": adatok betöltése
"tip_presettype": Válaszd ki, hogy milyen sablonok legyenek a menüben.
"action_waytags": vonal címkéinek módosítása
"action_pointtags": pont címkéinek módosítása
"action_poitags": POI címkéinek módosítása
"prompt_addtorelation": $1 hozzáadása kapcsolathoz
"existingrelation": Hozzáadás meglévő kapcsolathoz
"createrelation": Új kapcsolat létrehozása
"findrelation": Kapcsolat keresése
"norelations": Nincs kapcsolat a jelenlegi területen
"tip_selectrelation": Hozzáadás a kiválasztott kapcsolathoz
"prompt_welcome": Üdvözlünk az OpenStreetMapon!
"prompt_helpavailable": Új vagy? Segítségért nézd a jobb alsó sarkot.
"prompt_editsave": Szerk. mentéssel
"prompt_editlive": Szerk. élőben
"prompt_track": GPS nyomvonal átalakítása vonalakká
"prompt_launch": Külső URL indítása
"editinglive": Élő mód
"editingoffline": Offline mód
"save": Mentés
"tip_undo": "Visszavonás: $1 (Z)"
"error_noway": A(z) $1 nem található (talán már eltávolítottad?), így nem vonható vissza.
"error_nosharedpoint": A(z) $1 és a(z) $2 vonalaknak már nincs közös pontja, így nem vonható vissza a kettévágás.
"error_nopoi": A POI nem található (talán már eltávolítottad?), így nem vonható vissza.
"action_tidyway": vonal tisztítása
"delete": Törlés
"prompt_taggedpoints": Ezen a vonalon van néhány címkézett pont. Biztosan törlöd?
"a_way": vonal $1
"advice_waydragged": Vonal áthelyezve (Z a visszavonáshoz)
"action_moveway": vonal mozgatása
"action_splitway": vonal kettévágása
"action_mergeways": két vonal egyesítése
"advice_tagconflict": A címkék nem egyeznek - ellenőrizd (Z a visszavonáshoz)
"advice_nocommonpoint": A vonalaknak nincs közös pontjuk
"action_reverseway": vonal megfordítása
"action_insertnode": pont hozzáadása vonalhoz
"prompt_createparallel": Párhuzamos vonal készítése
"offset_dual": Osztott pályás út (D2)
"offset_motorway": Autópálya (D3)
"offset_narrowcanal": Keskeny csatorna
"offset_broadcanal": Széles csatorna
"offset_choose": Válassz eltolást (m)
"action_createparallel": párhuzamos vonalak készítése
"action_addpoint": pont hozzáadása a vonal végéhez
