"action_createpoi": vytváření bodu zájmu (POI)
"hint_pointselected": vybrán bod\n(shift-klik na bod\nzačne novou cestu)
"action_movepoint": posouvám bod
"hint_drawmode": přidej bod kliknutím\ndvojklik/Enter\nukončí cestu
"hint_overendpoint": "koncový bod:\nkliknutí pro napojení,\nshift-klik cesty sloučí"
"hint_overpoint": bod cesty:\nkliknutím cestu napojíte"
"gpxpleasewait": "Počkejte prosím: Zpracovávám GPX cestu"
"revert": Revertovat
"cancel": Zrušit
"prompt_revertversion": "Vrátit se ke dříve uložené verzi:"
"tip_revertversion": "Vyberte verzi, ke které se chcete vrátit:"
"action_movepoi": posunutí bodu záju (POI)
"tip_splitway": Rozdělit cestu ve vybraném bodě (X)
"tip_direction": Směr cesty (kliknutím otočíte)
"tip_clockwise": Po směru hodinových ručiček (kliknutím otočíte směr kruhové cesty)
"tip_anticlockwise": Proti směru hodinových ručiček (kliknutím otočíte směr kruhové cesty)
"tip_noundo": Není, co vzít zpět
"action_mergeways": sloučení dvou cest
"tip_gps": Zobrazit GPX stopy (GPS logy) (G)
"tip_options": Možnosti (vyberte si mapu na pozadí)
"tip_addtag": Přidat tag
"tip_addrelation": Přidat do relace
"tip_repeattag": Nastavit tagy předtím vybrané cesty(R)
"tip_alert": Vyskyla se chyba - pro více informací klikněte
"hint_toolong": "cesta je příliš dlouhá:\nrozdělte cestu na několik\nkratších úseků"
"hint_loading": načítám cesty
"prompt_welcome": Vítejte na OpenStreetMap
"prompt_introduction": "Klikněte jedno z tlačítek níže. Kliknutím na 'Start' začnete rovnou editovat mapu - změny se  projeví většinou při pravidelné úterní aktualizaci. Tlačítko 'Pískoviště' nastaví tréninkový režim, kdy se vaše změny nebudou ukládat a vy si budete moci editaci vyzkoušet na nečisto.\n\nTři hlavní pravidla projektu OpenStreetMap:\n\n"
"prompt_dontcopy": Nekopírujte z ostatních map - neporušujte autorská práva
"prompt_accuracy": Buďtě přesní - mapujte jen místa, kde jste skutečně byli
"prompt_enjoy": A hlavně, bavte se!
"dontshowagain": Příště tuto zprávu nezobrazovat
"prompt_start": Začít editovat
"prompt_practise": Tréninkový mód - změny se nebudou ukládat.
"practicemode": Tréninkový mód
"help": Nápověda
"prompt_help": Seznamte se s Potlatchem, tímto mapovým editorem
"track": Trasovat
"prompt_track": Převede vaši GPS stopu na (uzamčené) cesty, které následně můžete upravit.
"action_deletepoint": odstraňuji bod
"deleting": deleting
"action_cancelchanges": cancelling changes to
"emailauthor": \n\nPlease e-mail richard\@systemeD.net with a bug report, saying what you were doing at the time.
"error_connectionfailed": "Spojení s OpenStreetMap serverem selhalo. Vaše nedávné změny nemohly být uloženy.\n\nZkusit uložit změny znovu?"
"option_background": "Pozadí:"
"option_fadebackground": Zesvětlit pozadí
"option_thinlines": Používat tenké linky ve všech měřítkách mapy
"option_custompointers": Use pen and hand pointers
"tip_presettype": Zvolit skupinu předvoleb v menu.
"action_waytags": úprava tagů cesty
"action_pointtags": setting tags on a point
"action_poitags": setting tags on a POI
"action_addpoint": adding a node to the end of a way
"add": Přidat
"prompt_addtorelation": Přidat $1 k relace
"prompt_selectrelation": Vyberte existující relaci, nebo vytvořte novou.
"createrelation": Vytvořit novou relaci
"tip_selectrelation": Přidat k vybrané cestě
"action_reverseway": reversing a way
"tip_undo": "Zpět: $1 (Z)"
"error_noway": "Way $1 cannot be found (perhaps you've panned away?) so I can't undo."
"error_nosharedpoint": "Cesty $1 a $2 v současnosti nemaí společný bod, so I can't undo."
"error_nopoi": "The POI cannot be found (perhaps you've panned away?) so I can't undo."
"prompt_taggedpoints": Some of the points on this way are tagged. Really delete?
"action_insertnode": adding a node into a way
"action_splitway": rozděluji cestu
"editingmap": Editing map
"start": Start
"play": Play
"delete": Smazat
"a_way": $1 cestu
"a_poi": $1 bod zájmu
"action_moveway": moving a way
"way": Cesta
"point": Bod
"ok": Budiž
"existingrelation": Přidat k existující relaci
"findrelation": Najít relaci obsahující
"norelations": No relations in current area
"advice_toolong": Too long to unlock - please split into shorter ways
"advice_waydragged": Cesta posunuta (Z to undo)
"advice_tagconflict": "Tags don't match - please check"
"advice_nocommonpoint": Cesty nesdílí společný bod
"option_warnings": Zobrazovat plovoucí varování
"reverting": reverting
"prompt_helpavailable": You have unsaved changes. (To save in Potlatch, you should deselect the current way or point.)
